
-- ============================================
-- Auto-installed tables: BPROD, BROUTE, BOPE, BEQP, BAREA, BEQPG
-- ============================================

CREATE TABLE BPROD (
    PROD_ID                             CHAR(20)        NOT NULL,
    PROD_ID2                            CHAR(20)        NOT NULL,
    PROD_NAME                           CHAR(40)        NOT NULL,
    PROD_DESC                           CHAR(80)        NOT NULL,
    PROD_CAT                            CHAR(1)         NOT NULL,
    ROUTE_ID                            CHAR(12)        NOT NULL,
    ROUTE_VER                           CHAR(3)         NOT NULL,
    PRODUCT_KIND                        CHAR(10)        NOT NULL,
    LASRMARK_CAT                        CHAR(10)        NOT NULL,
    LASRMARK_PRINT_PTN1                 CHAR(10)        NOT NULL,
    LASRMARK_PRINT_PTN2                 CHAR(10)        NOT NULL,
    RFID_WRITE_FLG                      CHAR(1)         NOT NULL,
    INBOX_LM_CHECK_FLG                  CHAR(1)         NOT NULL,
    PN_CAT                              CHAR(10)        NOT NULL,
    SHIP_CAR_CODE                       CHAR(10)        NOT NULL,
    SHIP_BOX_FULL_NUM                   INT             NOT NULL,
    SHIP_BOX_NUM                        INT             NOT NULL,
    SHIP_BOX_PTN                        CHAR(10)        NOT NULL,
    MIX_BOX_CNT                         INT             NOT NULL,
    ODD_BOX_SHIP_FLG                    CHAR(1)         NOT NULL,
    SHIP_LABEL_PRINT_ID                 CHAR(30)        NOT NULL,
    SHIP_LABEL_PRINT_NUM                INT             NOT NULL,
    EP_MON_CON_ID                       CHAR(20)        NOT NULL,
    COND_EP_MON_CON_ID                  CHAR(20)        NOT NULL,
    PW_SMPL_CASET_CON_ID                CHAR(20)        NOT NULL,
    EP_SMPL_CASET_CON_ID                CHAR(20)        NOT NULL,
    AN_SMPL_CASET_CON_ID                CHAR(20)        NOT NULL,
    WHT_FLG                             CHAR(10)        NOT NULL,
    EG_FLG                              CHAR(10)        NOT NULL,
    CVD_FLG                             CHAR(10)        NOT NULL,
    SLICE_WIRE_PITCH                    DOUBLE          NOT NULL,
    CIR_WHEEL_STD                       INT             NOT NULL,
    NOTCH_WHEEL_STD                     INT             NOT NULL,
    FLT_GRIND_COUNT                     INT             NOT NULL,
    FIN_GRIND_COUNT                     INT             NOT NULL,
    LM_FACE_SPECIFIED_FLG               INT             NOT NULL,
    EDGING_REMOVE                       INT             NOT NULL,
    POLISH_KIND                         INT             NOT NULL,
    FLATNESS_RANK                       CHAR(1)         NOT NULL,
    FLT_POLISH_CROSS_LIFE_STD           CHAR(40)        NOT NULL,
    MIRROR_GRIND_GRAVITY                CHAR(1)         NOT NULL,
    FIN_POLISH_CROSS_LIFE_STD           CHAR(40)        NOT NULL,
    FOSB_INFOPAD_PLUG_POS               CHAR(40)        NOT NULL,
    SENTER_RITENER_EXIST                INT             NOT NULL,
    SHIP_LABEL_POS1                     CHAR(20)        NOT NULL,
    SHIP_LABEL_POS2                     CHAR(20)        NOT NULL,
    SHIP_LABEL_POS3                     CHAR(20)        NOT NULL,
    DESICCANT_EXIST                     INT             NOT NULL,
    DESICCANT_POS                       CHAR(20)        NOT NULL,
    KEM_PW_PROD_CODE                    CHAR(20)        NOT NULL,
    KEM_EP_PROD_CODE                    CHAR(20)        NOT NULL,
    KEM_AR_PROD_CODE                    CHAR(20)        NOT NULL,
    NOTCH_TOP_DEGREE                    INT             NOT NULL,
    NOTCH_TOP_ARCMIN                    INT             NOT NULL,
    NOTCH_TOP_ARCSEC                    INT             NOT NULL,
    NOTCH_LEFT_DEGREE                   INT             NOT NULL,
    NOTCH_LEFT_ARCMIN                   INT             NOT NULL,
    NOTCH_LEFT_ARCSEC                   INT             NOT NULL,
    SHIP_LABEL_PRINT_EXIST              INT             NOT NULL,
    RESERVE01                           CHAR(20)        NOT NULL,
    RESERVE02                           CHAR(20)        NOT NULL,
    RESERVE03                           CHAR(20)        NOT NULL,
    RESERVE04                           CHAR(20)        NOT NULL,
    RESERVE05                           CHAR(20)        NOT NULL,
    RESERVE06                           CHAR(20)        NOT NULL,
    RESERVE07                           CHAR(20)        NOT NULL,
    RESERVE08                           CHAR(20)        NOT NULL,
    RESERVE09                           CHAR(20)        NOT NULL,
    RESERVE10                           CHAR(20)        NOT NULL,
    RESERVE11                           CHAR(20)        NOT NULL,
    RESERVE12                           CHAR(20)        NOT NULL,
    RESERVE13                           CHAR(20)        NOT NULL,
    RESERVE14                           CHAR(20)        NOT NULL,
    RESERVE15                           CHAR(20)        NOT NULL,
    RESERVE16                           CHAR(20)        NOT NULL,
    RESERVE17                           CHAR(20)        NOT NULL,
    RESERVE18                           CHAR(20)        NOT NULL,
    RESERVE19                           CHAR(20)        NOT NULL,
    RESERVE20                           CHAR(20)        NOT NULL,
    RESERVE21                           CHAR(20)        NOT NULL,
    RESERVE22                           CHAR(20)        NOT NULL,
    RESERVE23                           CHAR(20)        NOT NULL,
    RESERVE24                           CHAR(20)        NOT NULL,
    RESERVE25                           CHAR(20)        NOT NULL,
    RESERVE26                           CHAR(20)        NOT NULL,
    RESERVE27                           CHAR(20)        NOT NULL,
    RESERVE28                           CHAR(20)        NOT NULL,
    RESERVE29                           CHAR(20)        NOT NULL,
    RESERVE30                           CHAR(20)        NOT NULL,
    RESERVE31                           CHAR(20)        NOT NULL,
    RESERVE32                           CHAR(20)        NOT NULL,
    RESERVE33                           CHAR(20)        NOT NULL,
    RESERVE34                           CHAR(20)        NOT NULL,
    RESERVE35                           CHAR(20)        NOT NULL,
    RESERVE36                           CHAR(20)        NOT NULL,
    RESERVE37                           CHAR(20)        NOT NULL,
    RESERVE38                           CHAR(20)        NOT NULL,
    RESERVE39                           CHAR(20)        NOT NULL,
    RESERVE40                           CHAR(20)        NOT NULL,
    RESERVE41                           CHAR(20)        NOT NULL,
    RESERVE42                           CHAR(20)        NOT NULL,
    RESERVE43                           CHAR(20)        NOT NULL,
    RESERVE44                           CHAR(20)        NOT NULL,
    RESERVE45                           CHAR(20)        NOT NULL,
    RESERVE46                           CHAR(20)        NOT NULL,
    RESERVE47                           CHAR(20)        NOT NULL,
    RESERVE48                           CHAR(20)        NOT NULL,
    RESERVE49                           CHAR(20)        NOT NULL,
    RESERVE50                           CHAR(20)        NOT NULL,
    PLANT_CAT                           CHAR(1)         NOT NULL,
    WRK_PLATE_TYPE                      CHAR(2)         NOT NULL,
    SMPL_FLG                            CHAR(1)         NOT NULL,
    RESIST_PER_CAT                      CHAR(10)        NOT NULL,
    DOPE_CAT_CZ                         CHAR(10)        NOT NULL,
    DOPE_CAT_EP                         CHAR(10)        NOT NULL,
    AXIS_CAT                            CHAR(10)        NOT NULL,
    PW_STD_RESIST_H                     DOUBLE          NOT NULL,
    PW_STD_RESIST_L                     DOUBLE          NOT NULL,
    EP_STD_THIK_H                       DOUBLE          NOT NULL,
    EP_STD_THIK_L                       DOUBLE          NOT NULL,
    EP_STD_RESIST_H                     DOUBLE          NOT NULL,
    EP_STD_RESIST_L                     DOUBLE          NOT NULL,
    MIX_CAT                             CHAR(1)         NOT NULL,
    SHIP_LOT_ID_NUM_CAT                 CHAR(1)         NOT NULL,
    SHIP_LABEL_PROD_NO                  CHAR(30)        NOT NULL,
    SHIP_LABEL_PART_NO                  CHAR(30)        NOT NULL,
    SHIP_LABEL_EC_NO                    CHAR(30)        NOT NULL,
    SHIP_LABEL_PROD_ID                  CHAR(30)        NOT NULL,
    SHIP_LABEL_CUSTOMER                 CHAR(40)        NOT NULL,
    STD_DIAMETER_C                      CHAR(10)        NOT NULL,
    STD_DIAMETER_H                      DOUBLE          NOT NULL,
    STD_DIAMETER_L                      DOUBLE          NOT NULL,
    STD_THIK_C                          CHAR(10)        NOT NULL,
    STD_THIK_H                          DOUBLE          NOT NULL,
    STD_THIK_L                          DOUBLE          NOT NULL,
    WAFER_FINISH                        CHAR(10)        NOT NULL,
    STD_EDGE_PIT                        CHAR(10)        NOT NULL,
    STD_LIFE_TIME                       CHAR(10)        NOT NULL,
    AXIS_CAT_TOLERANCE                  CHAR(20)        NOT NULL,
    SHIP_LABEL_REMARKS                  CHAR(30)        NOT NULL,
    CUSTOMER_PROD_ID                    CHAR(10)        NOT NULL,
    EP_TYPE                             CHAR(10)        NOT NULL,
    EPSUB_TYPE                          CHAR(10)        NOT NULL,
    EPSUB_STD_THIK_H                    DOUBLE          NOT NULL,
    EPSUB_STD_THIK_L                    DOUBLE          NOT NULL,
    EPSUB_STD_RESIST_H                  DOUBLE          NOT NULL,
    EPSUB_STD_RESIST_L                  DOUBLE          NOT NULL,
    SHIP_LABEL_METHOD                   CHAR(10)        NOT NULL,
    IMPURITY_DENSITY                    CHAR(10)        NOT NULL,
    SPC_CAT1                            CHAR(10)        NOT NULL,
    SPC_CAT2                            CHAR(10)        NOT NULL,
    SPC_CAT3                            CHAR(10)        NOT NULL,
    SPC_CAT4                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT5                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT6                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT7                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT8                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT9                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT10                           CHAR(10)        NOT NULL DEFAULT '',
    CUSTOMER_ID                         CHAR(20)        NOT NULL,
    CUSTOMER_NAME                       CHAR(120)       NOT NULL DEFAULT '',
    CUSTOMER_NAME_VER                   CHAR(120)       NOT NULL DEFAULT '',
    USER_NAME                           CHAR(120)       NOT NULL DEFAULT '',
    STD_DIAMETER                        CHAR(120)       NOT NULL DEFAULT '',
    STD_PULL_METHOD                     CHAR(120)       NOT NULL DEFAULT '',
    STD_POLISH_TYPE                     CHAR(120)       NOT NULL DEFAULT '',
    STD_CRY_DIR                         CHAR(120)       NOT NULL DEFAULT '',
    STD_DOPANT                          CHAR(120)       NOT NULL DEFAULT '',
    STD_BACK_SHIELD                     CHAR(120)       NOT NULL DEFAULT '',
    STD_NO_EDGECUT                      CHAR(120)       NOT NULL DEFAULT '',
    STD_THICKNESS                       CHAR(120)       NOT NULL DEFAULT '',
    STD_RESISTIVITY                     CHAR(120)       NOT NULL DEFAULT '',
    SUPPLIER                            CHAR(120)       NOT NULL DEFAULT '',
    PRODUCT_MAKER                       CHAR(120)       NOT NULL DEFAULT '',
    PRODUCT_ADRESS                      CHAR(120)       NOT NULL DEFAULT '',
    ROHS_FLG                            CHAR(120)       NOT NULL DEFAULT '',
    CUSTOMER_STD                        CHAR(120)       NOT NULL DEFAULT '',
    OXY_INCLUDE                         CHAR(120)       NOT NULL DEFAULT '',
    PLANT_CODE                          CHAR(120)       NOT NULL DEFAULT '',
    MESSAGE                             CHAR(120)       NOT NULL DEFAULT '',
    ASS_TERM                            CHAR(120)       NOT NULL DEFAULT '',
    PARTICLE                            CHAR(120)       NOT NULL DEFAULT '',
    BOW                                 CHAR(120)       NOT NULL DEFAULT '',
    WARP                                CHAR(120)       NOT NULL DEFAULT '',
    TTV                                 CHAR(120)       NOT NULL DEFAULT '',
    SUPPLIER_SPEC                       CHAR(120)       NOT NULL DEFAULT '',
    SUPPLIER_PART                       CHAR(120)       NOT NULL DEFAULT '',
    CUSTOMER_NAME_EN                    CHAR(120)       NOT NULL DEFAULT '',
    MATERIAL_ID                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_01                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_02                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_03                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_04                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_05                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_06                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_07                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_08                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_09                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_10                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_11                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_12                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_13                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_14                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_15                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_16                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_17                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_18                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_19                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_20                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_21                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_22                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_23                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_24                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_25                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_26                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_27                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_28                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_29                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_30                         CHAR(120)       NOT NULL DEFAULT '',
    REL_FLG                             CHAR(1)         NOT NULL DEFAULT 'E',
    COMP_FLG                            CHAR(1)         NOT NULL DEFAULT 'N',
    CRE_DATE                            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CRE_USER                            CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    LAST_DATE1                          TIMESTAMP       ,
    LAST_ACT1                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER1                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE2                          TIMESTAMP       ,
    LAST_ACT2                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER2                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE3                          TIMESTAMP       ,
    LAST_ACT3                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER3                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE4                          TIMESTAMP       ,
    LAST_ACT4                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER4                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE5                          TIMESTAMP       ,
    LAST_ACT5                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER5                          CHAR(20)        NOT NULL DEFAULT '',
    OWNER                               CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    OWNERG                              CHAR(10)        NOT NULL DEFAULT '',
    PERMISSION                          CHAR(10)        NOT NULL DEFAULT 'PUBLIC    ',
    LOCK_USER                           CHAR(20)        NOT NULL DEFAULT '',
    LOCK_TIME                           TIMESTAMP       ,
    "COMMENT"                           CHAR(128)       NOT NULL DEFAULT '',
    PRIMARY KEY (prod_id, prod_id, REL_FLG)
);

CREATE TABLE DPROD (
    PROD_ID                             CHAR(20)        NOT NULL,
    PROD_ID2                            CHAR(20)        NOT NULL,
    PROD_NAME                           CHAR(40)        NOT NULL,
    PROD_DESC                           CHAR(80)        NOT NULL,
    PROD_CAT                            CHAR(1)         NOT NULL,
    ROUTE_ID                            CHAR(12)        NOT NULL,
    ROUTE_VER                           CHAR(3)         NOT NULL,
    PRODUCT_KIND                        CHAR(10)        NOT NULL,
    LASRMARK_CAT                        CHAR(10)        NOT NULL,
    LASRMARK_PRINT_PTN1                 CHAR(10)        NOT NULL,
    LASRMARK_PRINT_PTN2                 CHAR(10)        NOT NULL,
    RFID_WRITE_FLG                      CHAR(1)         NOT NULL,
    INBOX_LM_CHECK_FLG                  CHAR(1)         NOT NULL,
    PN_CAT                              CHAR(10)        NOT NULL,
    SHIP_CAR_CODE                       CHAR(10)        NOT NULL,
    SHIP_BOX_FULL_NUM                   INT             NOT NULL,
    SHIP_BOX_NUM                        INT             NOT NULL,
    SHIP_BOX_PTN                        CHAR(10)        NOT NULL,
    MIX_BOX_CNT                         INT             NOT NULL,
    ODD_BOX_SHIP_FLG                    CHAR(1)         NOT NULL,
    SHIP_LABEL_PRINT_ID                 CHAR(30)        NOT NULL,
    SHIP_LABEL_PRINT_NUM                INT             NOT NULL,
    EP_MON_CON_ID                       CHAR(20)        NOT NULL,
    COND_EP_MON_CON_ID                  CHAR(20)        NOT NULL,
    PW_SMPL_CASET_CON_ID                CHAR(20)        NOT NULL,
    EP_SMPL_CASET_CON_ID                CHAR(20)        NOT NULL,
    AN_SMPL_CASET_CON_ID                CHAR(20)        NOT NULL,
    WHT_FLG                             CHAR(10)        NOT NULL,
    EG_FLG                              CHAR(10)        NOT NULL,
    CVD_FLG                             CHAR(10)        NOT NULL,
    SLICE_WIRE_PITCH                    DOUBLE          NOT NULL,
    CIR_WHEEL_STD                       INT             NOT NULL,
    NOTCH_WHEEL_STD                     INT             NOT NULL,
    FLT_GRIND_COUNT                     INT             NOT NULL,
    FIN_GRIND_COUNT                     INT             NOT NULL,
    LM_FACE_SPECIFIED_FLG               INT             NOT NULL,
    EDGING_REMOVE                       INT             NOT NULL,
    POLISH_KIND                         INT             NOT NULL,
    FLATNESS_RANK                       CHAR(1)         NOT NULL,
    FLT_POLISH_CROSS_LIFE_STD           CHAR(40)        NOT NULL,
    MIRROR_GRIND_GRAVITY                CHAR(1)         NOT NULL,
    FIN_POLISH_CROSS_LIFE_STD           CHAR(40)        NOT NULL,
    FOSB_INFOPAD_PLUG_POS               CHAR(40)        NOT NULL,
    SENTER_RITENER_EXIST                INT             NOT NULL,
    SHIP_LABEL_POS1                     CHAR(20)        NOT NULL,
    SHIP_LABEL_POS2                     CHAR(20)        NOT NULL,
    SHIP_LABEL_POS3                     CHAR(20)        NOT NULL,
    DESICCANT_EXIST                     INT             NOT NULL,
    DESICCANT_POS                       CHAR(20)        NOT NULL,
    KEM_PW_PROD_CODE                    CHAR(20)        NOT NULL,
    KEM_EP_PROD_CODE                    CHAR(20)        NOT NULL,
    KEM_AR_PROD_CODE                    CHAR(20)        NOT NULL,
    NOTCH_TOP_DEGREE                    INT             NOT NULL,
    NOTCH_TOP_ARCMIN                    INT             NOT NULL,
    NOTCH_TOP_ARCSEC                    INT             NOT NULL,
    NOTCH_LEFT_DEGREE                   INT             NOT NULL,
    NOTCH_LEFT_ARCMIN                   INT             NOT NULL,
    NOTCH_LEFT_ARCSEC                   INT             NOT NULL,
    SHIP_LABEL_PRINT_EXIST              INT             NOT NULL,
    RESERVE01                           CHAR(20)        NOT NULL,
    RESERVE02                           CHAR(20)        NOT NULL,
    RESERVE03                           CHAR(20)        NOT NULL,
    RESERVE04                           CHAR(20)        NOT NULL,
    RESERVE05                           CHAR(20)        NOT NULL,
    RESERVE06                           CHAR(20)        NOT NULL,
    RESERVE07                           CHAR(20)        NOT NULL,
    RESERVE08                           CHAR(20)        NOT NULL,
    RESERVE09                           CHAR(20)        NOT NULL,
    RESERVE10                           CHAR(20)        NOT NULL,
    RESERVE11                           CHAR(20)        NOT NULL,
    RESERVE12                           CHAR(20)        NOT NULL,
    RESERVE13                           CHAR(20)        NOT NULL,
    RESERVE14                           CHAR(20)        NOT NULL,
    RESERVE15                           CHAR(20)        NOT NULL,
    RESERVE16                           CHAR(20)        NOT NULL,
    RESERVE17                           CHAR(20)        NOT NULL,
    RESERVE18                           CHAR(20)        NOT NULL,
    RESERVE19                           CHAR(20)        NOT NULL,
    RESERVE20                           CHAR(20)        NOT NULL,
    RESERVE21                           CHAR(20)        NOT NULL,
    RESERVE22                           CHAR(20)        NOT NULL,
    RESERVE23                           CHAR(20)        NOT NULL,
    RESERVE24                           CHAR(20)        NOT NULL,
    RESERVE25                           CHAR(20)        NOT NULL,
    RESERVE26                           CHAR(20)        NOT NULL,
    RESERVE27                           CHAR(20)        NOT NULL,
    RESERVE28                           CHAR(20)        NOT NULL,
    RESERVE29                           CHAR(20)        NOT NULL,
    RESERVE30                           CHAR(20)        NOT NULL,
    RESERVE31                           CHAR(20)        NOT NULL,
    RESERVE32                           CHAR(20)        NOT NULL,
    RESERVE33                           CHAR(20)        NOT NULL,
    RESERVE34                           CHAR(20)        NOT NULL,
    RESERVE35                           CHAR(20)        NOT NULL,
    RESERVE36                           CHAR(20)        NOT NULL,
    RESERVE37                           CHAR(20)        NOT NULL,
    RESERVE38                           CHAR(20)        NOT NULL,
    RESERVE39                           CHAR(20)        NOT NULL,
    RESERVE40                           CHAR(20)        NOT NULL,
    RESERVE41                           CHAR(20)        NOT NULL,
    RESERVE42                           CHAR(20)        NOT NULL,
    RESERVE43                           CHAR(20)        NOT NULL,
    RESERVE44                           CHAR(20)        NOT NULL,
    RESERVE45                           CHAR(20)        NOT NULL,
    RESERVE46                           CHAR(20)        NOT NULL,
    RESERVE47                           CHAR(20)        NOT NULL,
    RESERVE48                           CHAR(20)        NOT NULL,
    RESERVE49                           CHAR(20)        NOT NULL,
    RESERVE50                           CHAR(20)        NOT NULL,
    PLANT_CAT                           CHAR(1)         NOT NULL,
    WRK_PLATE_TYPE                      CHAR(2)         NOT NULL,
    SMPL_FLG                            CHAR(1)         NOT NULL,
    RESIST_PER_CAT                      CHAR(10)        NOT NULL,
    DOPE_CAT_CZ                         CHAR(10)        NOT NULL,
    DOPE_CAT_EP                         CHAR(10)        NOT NULL,
    AXIS_CAT                            CHAR(10)        NOT NULL,
    PW_STD_RESIST_H                     DOUBLE          NOT NULL,
    PW_STD_RESIST_L                     DOUBLE          NOT NULL,
    EP_STD_THIK_H                       DOUBLE          NOT NULL,
    EP_STD_THIK_L                       DOUBLE          NOT NULL,
    EP_STD_RESIST_H                     DOUBLE          NOT NULL,
    EP_STD_RESIST_L                     DOUBLE          NOT NULL,
    MIX_CAT                             CHAR(1)         NOT NULL,
    SHIP_LOT_ID_NUM_CAT                 CHAR(1)         NOT NULL,
    SHIP_LABEL_PROD_NO                  CHAR(30)        NOT NULL,
    SHIP_LABEL_PART_NO                  CHAR(30)        NOT NULL,
    SHIP_LABEL_EC_NO                    CHAR(30)        NOT NULL,
    SHIP_LABEL_PROD_ID                  CHAR(30)        NOT NULL,
    SHIP_LABEL_CUSTOMER                 CHAR(40)        NOT NULL,
    STD_DIAMETER_C                      CHAR(10)        NOT NULL,
    STD_DIAMETER_H                      DOUBLE          NOT NULL,
    STD_DIAMETER_L                      DOUBLE          NOT NULL,
    STD_THIK_C                          CHAR(10)        NOT NULL,
    STD_THIK_H                          DOUBLE          NOT NULL,
    STD_THIK_L                          DOUBLE          NOT NULL,
    WAFER_FINISH                        CHAR(10)        NOT NULL,
    STD_EDGE_PIT                        CHAR(10)        NOT NULL,
    STD_LIFE_TIME                       CHAR(10)        NOT NULL,
    AXIS_CAT_TOLERANCE                  CHAR(20)        NOT NULL,
    SHIP_LABEL_REMARKS                  CHAR(30)        NOT NULL,
    CUSTOMER_PROD_ID                    CHAR(10)        NOT NULL,
    EP_TYPE                             CHAR(10)        NOT NULL,
    EPSUB_TYPE                          CHAR(10)        NOT NULL,
    EPSUB_STD_THIK_H                    DOUBLE          NOT NULL,
    EPSUB_STD_THIK_L                    DOUBLE          NOT NULL,
    EPSUB_STD_RESIST_H                  DOUBLE          NOT NULL,
    EPSUB_STD_RESIST_L                  DOUBLE          NOT NULL,
    SHIP_LABEL_METHOD                   CHAR(10)        NOT NULL,
    IMPURITY_DENSITY                    CHAR(10)        NOT NULL,
    SPC_CAT1                            CHAR(10)        NOT NULL,
    SPC_CAT2                            CHAR(10)        NOT NULL,
    SPC_CAT3                            CHAR(10)        NOT NULL,
    SPC_CAT4                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT5                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT6                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT7                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT8                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT9                            CHAR(10)        NOT NULL DEFAULT '',
    SPC_CAT10                           CHAR(10)        NOT NULL DEFAULT '',
    CUSTOMER_ID                         CHAR(20)        NOT NULL,
    CUSTOMER_NAME                       CHAR(120)       NOT NULL DEFAULT '',
    CUSTOMER_NAME_VER                   CHAR(120)       NOT NULL DEFAULT '',
    USER_NAME                           CHAR(120)       NOT NULL DEFAULT '',
    STD_DIAMETER                        CHAR(120)       NOT NULL DEFAULT '',
    STD_PULL_METHOD                     CHAR(120)       NOT NULL DEFAULT '',
    STD_POLISH_TYPE                     CHAR(120)       NOT NULL DEFAULT '',
    STD_CRY_DIR                         CHAR(120)       NOT NULL DEFAULT '',
    STD_DOPANT                          CHAR(120)       NOT NULL DEFAULT '',
    STD_BACK_SHIELD                     CHAR(120)       NOT NULL DEFAULT '',
    STD_NO_EDGECUT                      CHAR(120)       NOT NULL DEFAULT '',
    STD_THICKNESS                       CHAR(120)       NOT NULL DEFAULT '',
    STD_RESISTIVITY                     CHAR(120)       NOT NULL DEFAULT '',
    SUPPLIER                            CHAR(120)       NOT NULL DEFAULT '',
    PRODUCT_MAKER                       CHAR(120)       NOT NULL DEFAULT '',
    PRODUCT_ADRESS                      CHAR(120)       NOT NULL DEFAULT '',
    ROHS_FLG                            CHAR(120)       NOT NULL DEFAULT '',
    CUSTOMER_STD                        CHAR(120)       NOT NULL DEFAULT '',
    OXY_INCLUDE                         CHAR(120)       NOT NULL DEFAULT '',
    PLANT_CODE                          CHAR(120)       NOT NULL DEFAULT '',
    MESSAGE                             CHAR(120)       NOT NULL DEFAULT '',
    ASS_TERM                            CHAR(120)       NOT NULL DEFAULT '',
    PARTICLE                            CHAR(120)       NOT NULL DEFAULT '',
    BOW                                 CHAR(120)       NOT NULL DEFAULT '',
    WARP                                CHAR(120)       NOT NULL DEFAULT '',
    TTV                                 CHAR(120)       NOT NULL DEFAULT '',
    SUPPLIER_SPEC                       CHAR(120)       NOT NULL DEFAULT '',
    SUPPLIER_PART                       CHAR(120)       NOT NULL DEFAULT '',
    CUSTOMER_NAME_EN                    CHAR(120)       NOT NULL DEFAULT '',
    MATERIAL_ID                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_01                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_02                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_03                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_04                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_05                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_06                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_07                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_08                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_09                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_10                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_11                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_12                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_13                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_14                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_15                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_16                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_17                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_18                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_19                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_20                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_21                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_22                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_23                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_24                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_25                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_26                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_27                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_28                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_29                         CHAR(120)       NOT NULL DEFAULT '',
    SELF_DEF_30                         CHAR(120)       NOT NULL DEFAULT '',
    PRIMARY KEY (prod_id, prod_id)
);

CREATE TABLE BROUTE (
    ROUTE_ID                            CHAR(12)        NOT NULL,
    ROUTE_VER                           CHAR(3)         NOT NULL,
    SUB_RWK_CAT                         CHAR(1)         NOT NULL,
    ROUTE_CAT                           CHAR(10)        NOT NULL,
    ROUTE_NAME                          CHAR(40)        NOT NULL,
    ROUTE_DESC                          CHAR(80)        NOT NULL,
    REL_FLG                             CHAR(1)         NOT NULL DEFAULT 'E',
    COMP_FLG                            CHAR(1)         NOT NULL DEFAULT 'N',
    CRE_DATE                            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CRE_USER                            CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    LAST_DATE1                          TIMESTAMP       ,
    LAST_ACT1                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER1                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE2                          TIMESTAMP       ,
    LAST_ACT2                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER2                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE3                          TIMESTAMP       ,
    LAST_ACT3                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER3                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE4                          TIMESTAMP       ,
    LAST_ACT4                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER4                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE5                          TIMESTAMP       ,
    LAST_ACT5                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER5                          CHAR(20)        NOT NULL DEFAULT '',
    OWNER                               CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    OWNERG                              CHAR(10)        NOT NULL DEFAULT '',
    PERMISSION                          CHAR(10)        NOT NULL DEFAULT 'PUBLIC    ',
    LOCK_USER                           CHAR(20)        NOT NULL DEFAULT '',
    LOCK_TIME                           TIMESTAMP       ,
    "COMMENT"                           CHAR(128)       NOT NULL DEFAULT '',
    PRIMARY KEY (route_id, route_ver, REL_FLG)
);

CREATE TABLE DROUTE (
    ROUTE_ID                            CHAR(12)        NOT NULL,
    ROUTE_VER                           CHAR(3)         NOT NULL,
    SUB_RWK_CAT                         CHAR(1)         NOT NULL,
    ROUTE_CAT                           CHAR(10)        NOT NULL,
    ROUTE_NAME                          CHAR(40)        NOT NULL,
    ROUTE_DESC                          CHAR(80)        NOT NULL,
    PRIMARY KEY (route_id, route_ver)
);

CREATE TABLE BOPE (
    OPE_ID                              CHAR(8)         NOT NULL,
    OPE_NAME                            CHAR(40)        NOT NULL,
    OPE_DESC                            CHAR(80)        NOT NULL,
    OPE_PROPERTY                        CHAR(10)        NOT NULL,
    OPE_CAT_ID                          CHAR(10)        NOT NULL DEFAULT ' ',
    EQP_ID                              CHAR(10)        NOT NULL,
    RECIP_ID                            CHAR(20)        NOT NULL,
    PROCDATA_ID                         CHAR(13)        NOT NULL,
    MEAS_ID                             CHAR(13)        NOT NULL,
    FAM_LOT_HOLD_FLG                    CHAR(1)         NOT NULL,
    CARG_UNLOAD                         CHAR(10)        NOT NULL,
    CARG_UNLOAD2                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD3                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD4                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD5                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD6                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD7                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD8                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD9                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD10                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD11                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD12                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD13                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD14                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD15                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD16                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD17                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD18                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD19                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD20                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD21                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD22                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD23                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD24                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD25                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD26                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD27                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD28                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD29                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD30                       CHAR(10)        NOT NULL DEFAULT ' ',
    CAR_TYPE                            CHAR(2)         NOT NULL DEFAULT ' ',
    CAR_MODE                            CHAR(1)         NOT NULL,
    LOT_MIX_CAT                         CHAR(1)         NOT NULL,
    LOT_COLLECT_FLG                     CHAR(1)         NOT NULL,
    OPE_INSP_FLG                        CHAR(1)         NOT NULL,
    OPE_INSP_REG_CAR                    INT             NOT NULL,
    OPE_INSP_REG_LOT                    INT             NOT NULL,
    OPE_INSP_REG_PROD                   INT             NOT NULL,
    OPE_INSP_REG_RECIP                  INT             NOT NULL,
    OPE_INSP_ENF_WAF_NUM                INT             NOT NULL,
    PROC_UNIT                           CHAR(1)         NOT NULL,
    PROC_TIME                           CHAR(9)         NOT NULL,
    PROC_QTIME                          CHAR(9)         NOT NULL,
    HANDL_TIME                          CHAR(9)         NOT NULL,
    CARRY_PORT                          CHAR(10)        NOT NULL,
    LOT_FOLLOW_FLG                      CHAR(1)         NOT NULL DEFAULT 'N',
    REL_FLG                             CHAR(1)         NOT NULL DEFAULT 'E',
    COMP_FLG                            CHAR(1)         NOT NULL DEFAULT 'N',
    CRE_DATE                            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CRE_USER                            CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    LAST_DATE1                          TIMESTAMP       ,
    LAST_ACT1                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER1                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE2                          TIMESTAMP       ,
    LAST_ACT2                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER2                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE3                          TIMESTAMP       ,
    LAST_ACT3                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER3                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE4                          TIMESTAMP       ,
    LAST_ACT4                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER4                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE5                          TIMESTAMP       ,
    LAST_ACT5                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER5                          CHAR(20)        NOT NULL DEFAULT '',
    OWNER                               CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    OWNERG                              CHAR(10)        NOT NULL DEFAULT '',
    PERMISSION                          CHAR(10)        NOT NULL DEFAULT 'PUBLIC    ',
    LOCK_USER                           CHAR(20)        NOT NULL DEFAULT '',
    LOCK_TIME                           TIMESTAMP       ,
    "COMMENT"                           CHAR(128)       NOT NULL DEFAULT '',
    PRIMARY KEY (ope_id, REL_FLG)
);

CREATE TABLE DOPE (
    OPE_ID                              CHAR(8)         NOT NULL,
    OPE_NAME                            CHAR(40)        NOT NULL,
    OPE_DESC                            CHAR(80)        NOT NULL,
    OPE_PROPERTY                        CHAR(10)        NOT NULL,
    OPE_CAT_ID                          CHAR(10)        NOT NULL DEFAULT ' ',
    EQP_ID                              CHAR(10)        NOT NULL,
    RECIP_ID                            CHAR(20)        NOT NULL,
    PROCDATA_ID                         CHAR(13)        NOT NULL,
    MEAS_ID                             CHAR(13)        NOT NULL,
    FAM_LOT_HOLD_FLG                    CHAR(1)         NOT NULL,
    CARG_UNLOAD                         CHAR(10)        NOT NULL,
    CARG_UNLOAD2                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD3                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD4                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD5                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD6                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD7                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD8                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD9                        CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD10                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD11                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD12                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD13                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD14                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD15                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD16                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD17                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD18                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD19                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD20                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD21                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD22                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD23                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD24                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD25                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD26                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD27                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD28                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD29                       CHAR(10)        NOT NULL DEFAULT ' ',
    CARG_UNLOAD30                       CHAR(10)        NOT NULL DEFAULT ' ',
    CAR_TYPE                            CHAR(2)         NOT NULL DEFAULT ' ',
    CAR_MODE                            CHAR(1)         NOT NULL,
    LOT_MIX_CAT                         CHAR(1)         NOT NULL,
    LOT_COLLECT_FLG                     CHAR(1)         NOT NULL,
    OPE_INSP_FLG                        CHAR(1)         NOT NULL,
    OPE_INSP_REG_CAR                    INT             NOT NULL,
    OPE_INSP_REG_LOT                    INT             NOT NULL,
    OPE_INSP_REG_PROD                   INT             NOT NULL,
    OPE_INSP_REG_RECIP                  INT             NOT NULL,
    OPE_INSP_ENF_WAF_NUM                INT             NOT NULL,
    PROC_UNIT                           CHAR(1)         NOT NULL,
    PROC_TIME                           CHAR(9)         NOT NULL,
    PROC_QTIME                          CHAR(9)         NOT NULL,
    HANDL_TIME                          CHAR(9)         NOT NULL,
    CARRY_PORT                          CHAR(10)        NOT NULL,
    LOT_FOLLOW_FLG                      CHAR(1)         NOT NULL DEFAULT 'N',
    PRIMARY KEY (ope_id)
);

CREATE TABLE BEQP (
    EQP_ID                              CHAR(10)        NOT NULL,
    EQP_NAME                            CHAR(40)        NOT NULL,
    EQP_DESC                            CHAR(80)        NOT NULL,
    EQP_CAT                             CHAR(1)         NOT NULL,
    EQP_PROPERTY                        CHAR(10)        NOT NULL,
    EQP_MODE1                           CHAR(5)         NOT NULL,
    EQP_MODE2                           CHAR(5)         NOT NULL,
    EQP_MODE3                           CHAR(5)         NOT NULL,
    EQP_MODE4                           CHAR(5)         NOT NULL,
    EQP_MODE5                           CHAR(5)         NOT NULL,
    EQP_MODE6                           CHAR(5)         NOT NULL,
    EQP_MODE7                           CHAR(5)         NOT NULL,
    EQP_MODE8                           CHAR(5)         NOT NULL,
    EQP_MODE9                           CHAR(5)         NOT NULL,
    EQP_MODE10                          CHAR(5)         NOT NULL,
    WHAT_NEXT_MODE                      CHAR(1)         NOT NULL,
    ECS_RESRC_NAME                      CHAR(40)        NOT NULL,
    LOT_SEL_RULE1                       CHAR(1)         NOT NULL,
    LOT_SEL_RULE2                       CHAR(1)         NOT NULL,
    LOT_SEL_RULE3                       CHAR(1)         NOT NULL,
    LOT_SEL_RULE4                       CHAR(1)         NOT NULL,
    PM_FLG                              CHAR(1)         NOT NULL,
    FAB_ID                              CHAR(10)        NOT NULL,
    LINE_ID                             CHAR(10)        NOT NULL,
    WRK_PLATE_TYPE                      CHAR(2)         NOT NULL,
    GRAND_EQP                           CHAR(10)        NOT NULL,
    DSP_AREA                            CHAR(6)         NOT NULL,
    RP_RATE                             INT             NOT NULL,
    LINE_CNT                            INT             NOT NULL,
    UNIT_CNT                            INT             NOT NULL,
    MCS_RESRC_NAME                      CHAR(40)       ,
    ULRQ_WAIT_TIME                      INT             NOT NULL,
    REL_FLG                             CHAR(1)         NOT NULL DEFAULT 'E',
    COMP_FLG                            CHAR(1)         NOT NULL DEFAULT 'N',
    CRE_DATE                            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CRE_USER                            CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    LAST_DATE1                          TIMESTAMP       ,
    LAST_ACT1                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER1                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE2                          TIMESTAMP       ,
    LAST_ACT2                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER2                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE3                          TIMESTAMP       ,
    LAST_ACT3                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER3                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE4                          TIMESTAMP       ,
    LAST_ACT4                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER4                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE5                          TIMESTAMP       ,
    LAST_ACT5                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER5                          CHAR(20)        NOT NULL DEFAULT '',
    OWNER                               CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    OWNERG                              CHAR(10)        NOT NULL DEFAULT '',
    PERMISSION                          CHAR(10)        NOT NULL DEFAULT 'PUBLIC    ',
    LOCK_USER                           CHAR(20)        NOT NULL DEFAULT '',
    LOCK_TIME                           TIMESTAMP       ,
    "COMMENT"                           CHAR(128)       NOT NULL DEFAULT '',
    PRIMARY KEY (eqp_id, REL_FLG)
);

CREATE TABLE DEQP (
    EQP_ID                              CHAR(10)        NOT NULL,
    EQP_NAME                            CHAR(40)        NOT NULL,
    EQP_DESC                            CHAR(80)        NOT NULL,
    EQP_CAT                             CHAR(1)         NOT NULL,
    EQP_PROPERTY                        CHAR(10)        NOT NULL,
    EQP_MODE1                           CHAR(5)         NOT NULL,
    EQP_MODE2                           CHAR(5)         NOT NULL,
    EQP_MODE3                           CHAR(5)         NOT NULL,
    EQP_MODE4                           CHAR(5)         NOT NULL,
    EQP_MODE5                           CHAR(5)         NOT NULL,
    EQP_MODE6                           CHAR(5)         NOT NULL,
    EQP_MODE7                           CHAR(5)         NOT NULL,
    EQP_MODE8                           CHAR(5)         NOT NULL,
    EQP_MODE9                           CHAR(5)         NOT NULL,
    EQP_MODE10                          CHAR(5)         NOT NULL,
    WHAT_NEXT_MODE                      CHAR(1)         NOT NULL,
    ECS_RESRC_NAME                      CHAR(40)        NOT NULL,
    LOT_SEL_RULE1                       CHAR(1)         NOT NULL,
    LOT_SEL_RULE2                       CHAR(1)         NOT NULL,
    LOT_SEL_RULE3                       CHAR(1)         NOT NULL,
    LOT_SEL_RULE4                       CHAR(1)         NOT NULL,
    PM_FLG                              CHAR(1)         NOT NULL,
    FAB_ID                              CHAR(10)        NOT NULL,
    LINE_ID                             CHAR(10)        NOT NULL,
    WRK_PLATE_TYPE                      CHAR(2)         NOT NULL,
    GRAND_EQP                           CHAR(10)        NOT NULL,
    DSP_AREA                            CHAR(6)         NOT NULL,
    RP_RATE                             INT             NOT NULL,
    LINE_CNT                            INT             NOT NULL,
    UNIT_CNT                            INT             NOT NULL,
    MCS_RESRC_NAME                      CHAR(40)       ,
    ULRQ_WAIT_TIME                      INT             NOT NULL,
    PRIMARY KEY (eqp_id)
);

CREATE TABLE BAREA (
    AREA_ID                             CHAR(6)         NOT NULL,
    AREA_NAME                           CHAR(40)        NOT NULL,
    AREA_DESC                           CHAR(80)        NOT NULL,
    IP_ADRESS                           CHAR(15)        NOT NULL,
    REL_FLG                             CHAR(1)         NOT NULL DEFAULT 'E',
    COMP_FLG                            CHAR(1)         NOT NULL DEFAULT 'N',
    CRE_DATE                            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CRE_USER                            CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    LAST_DATE1                          TIMESTAMP       ,
    LAST_ACT1                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER1                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE2                          TIMESTAMP       ,
    LAST_ACT2                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER2                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE3                          TIMESTAMP       ,
    LAST_ACT3                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER3                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE4                          TIMESTAMP       ,
    LAST_ACT4                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER4                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE5                          TIMESTAMP       ,
    LAST_ACT5                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER5                          CHAR(20)        NOT NULL DEFAULT '',
    OWNER                               CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    OWNERG                              CHAR(10)        NOT NULL DEFAULT '',
    PERMISSION                          CHAR(10)        NOT NULL DEFAULT 'PUBLIC    ',
    LOCK_USER                           CHAR(20)        NOT NULL DEFAULT '',
    LOCK_TIME                           TIMESTAMP       ,
    "COMMENT"                           CHAR(128)       NOT NULL DEFAULT '',
    PRIMARY KEY (area_id, REL_FLG)
);

CREATE TABLE DAREA (
    AREA_ID                             CHAR(6)         NOT NULL,
    AREA_NAME                           CHAR(40)        NOT NULL,
    AREA_DESC                           CHAR(80)        NOT NULL,
    IP_ADRESS                           CHAR(15)        NOT NULL,
    PRIMARY KEY (area_id)
);

CREATE TABLE BEQPG (
    EQPG_ID                             CHAR(10)        NOT NULL,
    EQPG_NAME                           CHAR(40)        NOT NULL,
    EQPG_DESC                           CHAR(80)        NOT NULL,
    REL_FLG                             CHAR(1)         NOT NULL DEFAULT 'E',
    COMP_FLG                            CHAR(1)         NOT NULL DEFAULT 'N',
    CRE_DATE                            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CRE_USER                            CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    LAST_DATE1                          TIMESTAMP       ,
    LAST_ACT1                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER1                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE2                          TIMESTAMP       ,
    LAST_ACT2                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER2                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE3                          TIMESTAMP       ,
    LAST_ACT3                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER3                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE4                          TIMESTAMP       ,
    LAST_ACT4                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER4                          CHAR(20)        NOT NULL DEFAULT '',
    LAST_DATE5                          TIMESTAMP       ,
    LAST_ACT5                           CHAR(12)        NOT NULL DEFAULT '',
    LAST_USER5                          CHAR(20)        NOT NULL DEFAULT '',
    OWNER                               CHAR(20)        NOT NULL DEFAULT 'SYSTEM',
    OWNERG                              CHAR(10)        NOT NULL DEFAULT '',
    PERMISSION                          CHAR(10)        NOT NULL DEFAULT 'PUBLIC    ',
    LOCK_USER                           CHAR(20)        NOT NULL DEFAULT '',
    LOCK_TIME                           TIMESTAMP       ,
    "COMMENT"                           CHAR(128)       NOT NULL DEFAULT '',
    PRIMARY KEY (eqpg_id, REL_FLG)
);

CREATE TABLE DEQPG (
    EQPG_ID                             CHAR(10)        NOT NULL,
    EQPG_NAME                           CHAR(40)        NOT NULL,
    EQPG_DESC                           CHAR(80)        NOT NULL,
    PRIMARY KEY (eqpg_id)
);
