-- Minimal checks for tables without curated config

INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','SAVE',1,'NOTNULL','EQP_ID',NULL,NULL,NULL,'EQP_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','SAVE',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','SAVE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','RELEASE',1,'NOTNULL','EQP_ID',NULL,NULL,NULL,'EQP_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','RELEASE',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','RELEASE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','RELEASE',10,'RELEASE_PARAM','EQP_ID','DEQP_MAILADRESS',NULL,NULL,NULL);
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','DELETE',1,'NOTNULL','EQP_ID',NULL,NULL,NULL,'EQP_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','DELETE',2,'STAT_Y',NULL,NULL,NULL,NULL,'Not released');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','DELETE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','EDITCOMP',1,'NOTNULL','EQP_ID',NULL,NULL,NULL,'EQP_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','EDITCOMP',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','EDITCOMP',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BEQP_MAILADRESS','EDITCOMP',4,'COMP_N',NULL,NULL,NULL,NULL,'Already complete');

INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','SAVE',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','SAVE',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','SAVE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','RELEASE',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','RELEASE',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','RELEASE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','RELEASE',10,'RELEASE_PARAM','PROD_ID','DPROD_20210412',NULL,NULL,NULL);
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','DELETE',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','DELETE',2,'STAT_Y',NULL,NULL,NULL,NULL,'Not released');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','DELETE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','EDITCOMP',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','EDITCOMP',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','EDITCOMP',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210412','EDITCOMP',4,'COMP_N',NULL,NULL,NULL,NULL,'Already complete');

INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','SAVE',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','SAVE',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','SAVE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','RELEASE',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','RELEASE',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','RELEASE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','RELEASE',10,'RELEASE_PARAM','PROD_ID','DPROD_20210414',NULL,NULL,NULL);
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','DELETE',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','DELETE',2,'STAT_Y',NULL,NULL,NULL,NULL,'Not released');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','DELETE',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','EDITCOMP',1,'NOTNULL','PROD_ID',NULL,NULL,NULL,'PROD_ID required');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','EDITCOMP',2,'STAT_N',NULL,NULL,NULL,NULL,'Not editable');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','EDITCOMP',3,'LOCK_FREE',NULL,NULL,NULL,NULL,'Locked');
INSERT INTO SM_CHECK_DEF (TABLE_ID,CHECK_TYPE,CHECK_ORDER,CHECK_KIND,FIELD_NAME,REF_TABLE,REF_FIELD,EXPECT_VALUE,ERR_MSG) VALUES ('TBLID_BPROD_20210414','EDITCOMP',4,'COMP_N',NULL,NULL,NULL,NULL,'Already complete');

