-- SYSDATA from Initial_Data
INSERT INTO SYSDATA VALUES ('*', '15AN11', '375', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '15AN12', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '15AN13', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '25AN21', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '25AN22', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN301', '160', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN302', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN303', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN304', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN305', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN306', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN307', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN308', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN309', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN310', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN311', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN312', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN313', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN314', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN315', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN316', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN317', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN318', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN319', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN32', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN320', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN321', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN322', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN323', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN324', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN325', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN33', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN34', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN35', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', '35AN36', '125', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '1', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '10', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '11', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '12', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '13', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '2', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '3', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '4', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '5', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '6', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '7', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '8', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'A_BLK_PICK', '9', 'Y');
INSERT INTO SYSDATA VALUES ('*', 'ACTIO55', '1', 'Undefined');
INSERT INTO SYSDATA VALUES ('*', 'ACTION', '1', 'Eqpt HOLD');
INSERT INTO SYSDATA VALUES ('*', 'ACTION2', '1', 'Product HOLD');
INSERT INTO SYSDATA VALUES ('*', 'ACTION3', '1', 'Undefined');
INSERT INTO SYSDATA VALUES ('*', 'ACTION4', '1', 'Undefined');
INSERT INTO SYSDATA VALUES ('*', 'ACTION5', '1', 'Undefined');
INSERT INTO SYSDATA VALUES ('*', 'AE_FAB_EQP', '33AE303', 'Eqpt name list to move FAB from alkali etching process');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'ABNOR_CAR', '00000111');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'CASETTE_ABNORMAL', '00001111');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'EQP_ERR', '00000000');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'NO_CHK_LOT', '00000000');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'NO_EMPTY_CAR', '00000000');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'NO_MONITOR', '00000000');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'SYSTEM_ERR', '00000000');
INSERT INTO SYSDATA VALUES ('*', 'ALM_CAT', 'XFER_ERR', '00000100');
INSERT INTO SYSDATA VALUES ('*', 'ALM_STAT', 'C', 'Completed');
INSERT INTO SYSDATA VALUES ('*', 'ALM_STAT', 'D', 'Under processing');
INSERT INTO SYSDATA VALUES ('*', 'ALM_STAT', 'O', 'Not started');
INSERT INTO SYSDATA VALUES ('*', 'ALM_STAT', 'U', 'Under processing');
INSERT INTO SYSDATA VALUES ('*', 'AN_BOATNO_MAX', '85', 'Maximum number of anneal eqpt port');
INSERT INTO SYSDATA VALUES ('*', 'ANSIDE_MONI_ROUTE', 'R_ANSD_1', 'Route for anneal side dummy material place');
INSERT INTO SYSDATA VALUES ('*', 'ANSIDE_MONI_ROUTE', 'R_MM_0004', 'Route for anneal side dummy material place');
INSERT INTO SYSDATA VALUES ('*', 'ANSIDE_MONI_ROUTE', 'R_MM_0040', 'Route for anneal side dummy material place');
INSERT INTO SYSDATA VALUES ('*', 'ASS_CAT', '0', 'CZ assurance');
INSERT INTO SYSDATA VALUES ('*', 'ASS_CAT', '1', 'PW assurance');
INSERT INTO SYSDATA VALUES ('*', 'ASS_CAT', '2', 'Small lot');
INSERT INTO SYSDATA VALUES ('*', 'ASS_CAT', '3', 'Cassette lot');
INSERT INTO SYSDATA VALUES ('*', 'ASS_CAT', '4', 'Wafer');
INSERT INTO SYSDATA VALUES ('*', 'ASS_UNIT_ID', 'AR_BACTH_NO', 'Anneal batch No');
INSERT INTO SYSDATA VALUES ('*', 'ASS_UNIT_ID', 'ASS_BLOCK_ID', 'Assurance block ID');
INSERT INTO SYSDATA VALUES ('*', 'ASS_UNIT_ID', 'ASS_LOT_ID', 'Assurance block ID');
INSERT INTO SYSDATA VALUES ('*', 'ASS_UNIT_ID', 'SML_LOT_ID', 'small lot ID');
INSERT INTO SYSDATA VALUES ('*', 'BATCH_FORM_CAT', '0', 'batch group');
INSERT INTO SYSDATA VALUES ('*', 'BATCH_FORM_CAT', '1', 'cancel batch group');
INSERT INTO SYSDATA VALUES ('*', 'BLK_HOL_TM', '*', '30');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'AVE', 'AVE');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'CPY', 'COPY');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'DIV', 'DIV');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'ECL', 'ECALC');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'ICL', 'ICALC');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'JDG', 'JUDGE');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'MAX', 'MAX');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'MIN', 'MIN');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'SQRT', 'SQRT');
INSERT INTO SYSDATA VALUES ('*', 'CALC_CODE', 'STD', 'STD');
INSERT INTO SYSDATA VALUES ('*', 'CAR_LOAD_TYPE', 'C1', 'cassette');
INSERT INTO SYSDATA VALUES ('*', 'CAR_LOAD_TYPE', 'F1', 'FOSB');
INSERT INTO SYSDATA VALUES ('*', 'CAR_LOAD_TYPE', 'U1', 'FOUP');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '0', 'Carrier ExChange - Backward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '1', 'Carrier ExChange - Forward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '2', 'Carrier ExChange - Parallel');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '3', 'Same Carrier - Return');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '4', 'Carrier ExChange - Reverse Backward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '5', 'Carrier ExChange - Reverse Forward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', '6', 'Carrier ExChange - Reverse Parallel');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', 'A', 'Regeneration - Backward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', 'B', 'Regeneration - Forward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', 'C', 'Regeneration - Reverse Backward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_MODE', 'D', 'Regeneration - Reverse Forward');
INSERT INTO SYSDATA VALUES ('*', 'CAR_OUT_DEST', 'F6S908', 'Stock-out port name');
INSERT INTO SYSDATA VALUES ('*', 'CAR_OUT_DEST', 'F6S909', 'Stock-out port name');
INSERT INTO SYSDATA VALUES ('*', 'CAR_OUT_DEST', 'F6S910', 'Stock-out port name');
INSERT INTO SYSDATA VALUES ('*', 'CAR_OUT_DEST', 'F6S911', '[F6S911] Wrapping room Stock-put conveyor 2');
INSERT INTO SYSDATA VALUES ('*', 'CAR_OUT_DEST', 'F6S912', 'Stock-out port name');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'BL', 'Block');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'NG', 'NG_CAR_TYPE');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'O1', 'OC(13) EMPAK');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'O2', 'OC(15) PFA');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'O3', 'OC(25)7mm');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'O4', 'OC(25)10mm');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'O9', 'OC(13) PFA');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'OX', 'OC(15) PFA reserve');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S1', 'FOSB(25) MW300G');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S2', 'FOSB(25) KT3002D');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S3', 'FOSB(13) EMPAK');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S4', 'FOSB(25) WIN300S-A');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S5', 'FOSB(25) MW300F');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S6', 'FOSB(25) WIN300S');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S7', 'FOSB(25) KT3004A2');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S8', 'FOSB(25) KT3004A3');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'S9', 'FOSB(25) SB300');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SA', 'FOSB(25) KT3004A2Rev2(tentative)');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SB', 'FOSB(25) SB300-06EN4');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SC', 'FOSB(25) KT3002DE');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SD', 'FOSB(25) MW300GT');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SE', 'FOSB(25) SB300-06EN6');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SF', 'FOSB(25) KT3004A4');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'SG', 'FOSB(25) KT3004A2(ID)');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'T1', 'Tray');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'T2', 'WetTray');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'U1', 'FOUP(25)');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'U2', '-');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'VV', 'WT(25) PFA');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'W1', 'TOYO work plate');
INSERT INTO SYSDATA VALUES ('*', 'CAR_TYPE', 'W2', 'NTC work plate');
INSERT INTO SYSDATA VALUES ('*', 'CARSTATS', 'A', 'A:ABNORMAL');
INSERT INTO SYSDATA VALUES ('*', 'CARSTATS', 'E', 'E:Not UseiECSj');
INSERT INTO SYSDATA VALUES ('*', 'CARSTATS', 'M', 'M:MAINTENANCE');
INSERT INTO SYSDATA VALUES ('*', 'CARSTATS', 'N', 'N:NOMAL');
INSERT INTO SYSDATA VALUES ('*', 'CASSETTE_CAT', 'C', 'Tray');
INSERT INTO SYSDATA VALUES ('*', 'CASSETTE_CAT', 'O', 'Open Cassette');
INSERT INTO SYSDATA VALUES ('*', 'CASSETTE_CAT', 'S', 'FOSB');
INSERT INTO SYSDATA VALUES ('*', 'CASSETTE_CAT', 'T', 'Tray');
INSERT INTO SYSDATA VALUES ('*', 'CASSETTE_CAT', 'U', 'FOUP');
INSERT INTO SYSDATA VALUES ('*', 'CASSETTE_CAT', 'W', 'Work plate');
INSERT INTO SYSDATA VALUES ('*', 'CHK_CAT', '1', 'Restriction on input check');
INSERT INTO SYSDATA VALUES ('*', 'CHK_CAT', '2', 'Life check');
INSERT INTO SYSDATA VALUES ('*', 'CMP_MAXCNT', '20', 'Maximum number of waiting lots for shipping compiler process');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '1', 'No count');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '2', 'Cassette number');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '3', 'Wafer number');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '4', 'Batch number');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '5', 'Process data item ID');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '6', 'EP film thickness by film number');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '7', 'Cumulative value of Process data item ID');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '8', 'days number');
INSERT INTO SYSDATA VALUES ('*', 'CNT_METHOD', '9', 'Hours');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'ALM_CODE', 'Alarm code');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'BATCH_CAT', 'Batch category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'BLOCK_STAT', 'block status category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'CAR_TYPE', 'carrier type');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'CASSETTE_CAT', 'cassette category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'CNT_METH', 'count method');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'DSP_AREA', 'DSP area');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'FABID', 'FAB ID');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'GRAND_EQP', 'Grand group code');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'IL_INSP_CAT', 'Inline inspection category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'IL_PRE_CAT', 'Inline Pre-evaluation category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'ITEMIZED_ITEM', 'ITEMIZED item');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'ITEMIZED_REC_CAT', 'ITEMIZED record category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'LABEL_TYPE', 'Label type');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'LINEID', 'Line ID');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'MEAS_DATA_ITEMG', 'Measurement data item group');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'MEAS_UNIT', 'Measurement unit');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'MODULE_CAT', 'Module Category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'MRG_RSN_CODE', 'Reason code of merge operation');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'MTL_ITEMG', 'Material item group');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'OPE_CAT', 'Operation category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'PRODUCT_KIND2', 'Product kind');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'REJRSN_CODE_CAT', 'Reject reason code category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'REJRSN_CODE_STGG_CAT', 'Reject reason code Stage Group category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'ROUTE_CAT', 'Route category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'RWK_RSN_CODE', 'Rework reason code');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'STG_PROPERTY', 'Stage property');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'STGG_CAT', 'Stage group category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'TSHEET_TYPE', 'T-Sheet Type');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'UNDER_CAT', 'Direct category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'USER_CAT', 'User category');
INSERT INTO SYSDATA VALUES ('*', 'CODE_CAT', 'WRK_PLATE_TYPE', 'Work plate type');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A1', 'Slice compiler: small lot');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A2', 'Slice compiler: taking sample wafer');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A3', 'Slice compiler: Assurance lot');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A4', 'Slice compiler: Classified sample');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A5', 'Slice compiler: Re-sampling');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A6', 'Slice compiler: Re-compiling');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A7', 'Slice compiler: small lot 170kp');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A8', 'Slice compiler: Re-sampling 170kp');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'A9', 'Slice compiler: Re-compiling 170kp');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'B1', 'Ship compiler: Ship compiler');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'B2', 'Ship compiler: Classifying sample');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'B3', 'Ship compiler: EP sub / Anneal');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'B4', 'Ship compiler: Re-sampling');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'B5', 'Ship compiler: Inline lot');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'B7', 'Ship compiler: shape sorting');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'C1', 'RP compiler: Rework (Combine)');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'C2', 'RP compiler: Rework');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'C3', 'RP compiler: Taking Inline sample');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'C4', 'RP compiler: Classifying Inline sample');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'C5', 'RP compiler: Reversal wafer');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'D0', 'Simple moving');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'D1', 'Simple moving (PFA reversal)');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'F1', 'Pre-DSP compiling (170kp)');
INSERT INTO SYSDATA VALUES ('*', 'COMP_IND_CAT', 'F2', 'Pre-DSP compiling (130kp)');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', '1', 'Every Sunday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', '3', 'Every Tuesday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', '4', 'Every Wednesday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', '5', 'Every Thursday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', '6', 'Every Friday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', '7', 'Every Saturday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', 'D', 'Everyday');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', 'M', 'Once in month');
INSERT INTO SYSDATA VALUES ('*', 'CYCLE', 'W', 'Every Monday');
INSERT INTO SYSDATA VALUES ('*', 'CZ_PW_CAT', '0', 'CZ');
INSERT INTO SYSDATA VALUES ('*', 'CZ_PW_CAT', '1', 'PW');
INSERT INTO SYSDATA VALUES ('*', 'DATA_TYPE', 'C', 'Code');
INSERT INTO SYSDATA VALUES ('*', 'DATA_TYPE', 'F', 'Float');
INSERT INTO SYSDATA VALUES ('*', 'DATA_TYPE', 'I', 'Int');
INSERT INTO SYSDATA VALUES ('*', 'DATA_TYPE', 'S', 'String');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B100', 'Loader');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B101', 'Good product');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B102', 'Fractions product');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B103', 'Sample');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B104', 'Re-wash');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B105', 'Re-polish');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B106', 'Reject');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B300', 'Loader');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B301', 'Good product');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B302', 'Fractions product');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B303', 'Sample');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B304', 'Re-wash');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B305', 'Re-polish');
INSERT INTO SYSDATA VALUES ('*', 'DEST_TYPE', 'B306', 'Reject');
INSERT INTO SYSDATA VALUES ('*', 'DPROD_FIELD', 'LOCAL_LOT_CAT', 'Local lot category');
INSERT INTO SYSDATA VALUES ('*', 'DSP_CARG', 'FOU_25_PDC', '1');
INSERT INTO SYSDATA VALUES ('*', 'DSP_CLN_LOAD_PORT', 'DC4022', 'Loading port after DSP cleaning');
INSERT INTO SYSDATA VALUES ('*', 'DUMMY_CAT', 'D', 'Side dummy lot');
INSERT INTO SYSDATA VALUES ('*', 'EP_ASS_UNIT_CAT', '0', 'Assurance by between monitor lots');
INSERT INTO SYSDATA VALUES ('*', 'EP_ASS_UNIT_CAT', '1', 'Assurance by head lot');
INSERT INTO SYSDATA VALUES ('*', 'EQP_CAT', 'D', 'Dummy equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_CAT', 'R', 'Eqpt to remain wafer operation history');
INSERT INTO SYSDATA VALUES ('*', 'EQP_CAT', 'U', 'Normal equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'FULL', 'Full Auto');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'MANU', 'Manu');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'SEMI', 'Semi');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'SEMI2', 'Semi2');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'SEMI3', 'Semi3');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'SEMI4', 'Semi4');
INSERT INTO SYSDATA VALUES ('*', 'EQP_MODE', 'SMI2A', 'Semi2A');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', '', 'Normal equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AN_FRCT', 'AN fraction product place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AN_INV_IND', 'AN input order');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AN_POLISH', 'AN polish stock place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AN_REJECT', 'AN reject stock place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AN_RP', 'AN defect product place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AR_ANNEAL', 'Anneal');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'AT_MOUNT', 'Mounter equipment (auto)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'BL_XRAY_RE', 'X-ray measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'BMD_MEAS', 'BMD measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'CLEAN', 'Cleaning machine');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'CV_INV_IND', 'CVD input order');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'CVD', 'CVD');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'CW_EMP_CLN', 'Empty cassette cleaning machine');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'DSP', 'DSP');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'DSP_CLN', 'Cleaning machine after DSP');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EG_INV_IND', 'EG input order');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_FRCT', 'EP fraction product place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_LOTPLAN', 'EP input order plan dummy Eqpt');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_OPE', 'EP reaction Equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_POLISH', 'EP polish stock place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_REJECT', 'EP reject stock place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_RP', 'AN defect product place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'EP_VS_INSP', 'EP Growth appearance');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'GF_MEAS', 'GF measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'GRAN_CLN', 'Cleaning machine after Chamfering');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'GRND', 'surface grind');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'HEAT_OSF', 'OSF thermal process');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'HEAT_TRE', 'Thermal process');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'INSP_STK', 'sample inspection place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'LAP_CLN', 'Cleaning machine after LAP');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'LD_CHK_EQP', 'Check machine for loader port');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'LDL_MEAS', 'L/DL measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'LSW', 'LSW');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'LT_MEAS', 'LT measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'MN_MOUNT', 'Mounter equipment (Manu)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'MON_STK', 'Monitor lot place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'MOUNT6', 'Mounter equipment (170kp)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'NML_BLK', 'Normal block equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'OI_MEAS', 'OI measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'OSF_MEAS', 'OSF measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PACK', 'Package');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PS_MOUNT', 'Mounter equipment (Manu)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_DMNT', 'Separation cleaning');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_FRCT', 'PW fraction product place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_INV_IND', 'Chamfering input order');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_LM', 'laser mark');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_MGRAN', 'Mirror chamfering machine');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_POLISH', 'PW polish stock place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_REJECT', 'PW reject stock place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_RP', 'PW defect place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'PW_SLICE', 'Slice');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'QA_APP', 'QA judgment dummy equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'RES_MEAS', 'Resistivity measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SBW_LBW', 'Shape measurement equipment');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SH_CMP_1_S', 'Ship compiler preparation(PW ship compile)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SH_CMP_3_S', 'Ship compiler preparation (EP sub / Anneal compile)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SH_CMP_4_S', 'Ship compiler preparation(EP ship compile)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SH_CMP_5_S', 'Ship compiler preparing (AN ship compile)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SHIP_CMP', 'Ship compiler');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SORT_FRCT', 'Shape sorting  Fractions product place');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'SPV_MEAS', 'SPV measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'THICK_MEAS', 'Film thickness measurement');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'VS_INSP', 'Visual inspection');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'WAF_GRND', 'Wafer polishing and cleaning');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'WAF_GRND6', 'Wafer polishing and cleaning (170kp)');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'WASH', 'Alkali cleaning');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'WETTRAY', 'Cleaning wet tray');
INSERT INTO SYSDATA VALUES ('*', 'EQP_PROPERTY', 'WT_INV_IND', 'WHT input order');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'DOWN', 'DOWN');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'ENG', 'ENG : engineering');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'HOLD', 'Waiting for film thicknes meas result');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'OFF', 'OFF: Out of service');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'OTHER', 'OTHER');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'PM', 'PM preventive maintenance');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'READY', 'READY');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'RUN', 'RUN: Processing');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'SETUP', 'SETUP: set up');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'WAIT', 'WAIT Waiting for cassette exchanging');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'WTHUM', 'WTHUM: waiting for operator');
INSERT INTO SYSDATA VALUES ('*', 'EQP_STAT', 'WTMAT', 'WTMAT: waiting for material');
INSERT INTO SYSDATA VALUES ('*', 'EXIST_JDG_CAT', '0', 'None');
INSERT INTO SYSDATA VALUES ('*', 'EXIST_JDG_CAT', '1', 'Judged');
INSERT INTO SYSDATA VALUES ('*', 'FABID', 'FABID', 'FAB ID');
INSERT INTO SYSDATA VALUES ('*', 'FOLLOW_LOT', '0', 'ALL');
INSERT INTO SYSDATA VALUES ('*', 'FOLLOW_LOT', '1', 'Family during processing');
INSERT INTO SYSDATA VALUES ('*', 'FOLLOW_LOT', '2', 'Machining waiting Family');
INSERT INTO SYSDATA VALUES ('*', 'FOSB_LABEL', 'FB', 'FOSB');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'CC', 'CC Cancel for compile preparation');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'EM', 'EM Moving to shape sorting machine');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'HO', 'HO Hold');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'HR', 'HR Hold release');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'KL', 'KY Generating KYK Lot');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'LD', 'LD Lot Split');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'LE', 'LE Lot selection error');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'LG', 'LG Lot generating');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'LH', 'LH Lot generating');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'LM', 'LM Lot merge');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'LO', 'LO Lot out (Reject all )');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'OA', 'OA Operation cancel');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'OC', 'OC Operation Comp');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'OS', 'OS Operation start');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'PC', 'PC Update specific code');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'QL', 'QL Generating Q lot');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'RC', 'RC Rework route change');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'SC', 'SC Subroute Change');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'SO', 'SO Sublot out');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'SS', 'SS Select next lot');
INSERT INTO SYSDATA VALUES ('*', 'HIS_CAT', 'VU', 'VU lot version up');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_STAT', 'F', 'F holding waiting');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_STAT', 'H', 'H HOLD');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'BH', 'Hold for generating lot');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'CH', 'System hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'FH', 'Future hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'LH', 'Lot hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'MH', 'Merge hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'OH', 'Holding Family lot');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'PH', 'Process hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'QH', 'QA hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'SH', 'SPC hold');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'WH', 'Holding for retuurning to main route');
INSERT INTO SYSDATA VALUES ('*', 'HOLD_TYPE', 'XH', 'Compiler hold');
INSERT INTO SYSDATA VALUES ('*', 'IL_BL_CAT', 'B', 'BLOCK');
INSERT INTO SYSDATA VALUES ('*', 'INP_MODE', 'A', 'Auto only');
INSERT INTO SYSDATA VALUES ('*', 'INP_MODE', 'B', 'Both');
INSERT INTO SYSDATA VALUES ('*', 'INP_MODE', 'C', 'Calculate');
INSERT INTO SYSDATA VALUES ('*', 'INP_MODE', 'O', 'Manual Only');
INSERT INTO SYSDATA VALUES ('*', 'INSP_CAT', 'N', 'Normal inspection');
INSERT INTO SYSDATA VALUES ('*', 'INSP_CAT', 'S', 'Special inspection');
INSERT INTO SYSDATA VALUES ('*', 'INSP_LABEL', 'INSP_AN', 'AN inpsepection');
INSERT INTO SYSDATA VALUES ('*', 'INSP_LABEL', 'INSP_EP', 'EP inspection');
INSERT INTO SYSDATA VALUES ('*', 'INSP_LABEL', 'INSP_PW', 'PW inspection');
INSERT INTO SYSDATA VALUES ('*', 'INTR_DSPAREA_SEL', 'Y', 'Lot selection between DSP areas');
INSERT INTO SYSDATA VALUES ('*', 'JDG_RST_CAT', '', 'Not measured');
INSERT INTO SYSDATA VALUES ('*', 'JDG_RST_CAT', '0', 'OK');
INSERT INTO SYSDATA VALUES ('*', 'JDG_RST_CAT', '1', 'NG');
INSERT INTO SYSDATA VALUES ('*', 'JDG_RST_CAT', '9', 'N/A');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_CAT', '1', 'Inpsection label');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_CAT', '2', 'cassette label in process');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_CAT', '3', 'FOSB label');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_CAT', '4', 'Work plate label');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_CAT', '5', 'Ship label');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_PRINT_ID', 'OPE_LABEL_1', 'OPE_LABEL_1');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_PRINT_ID', 'OPE_LABEL_2', 'OPE_LABEL_2');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_PRINT_ID', 'OPE_LABEL_3', 'OPE_LABEL_3');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_PRINT_ID', 'OPE_TYPE_1', 'OPE_TYPE_1');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_PRINT_ID', 'OPE_TYPE_2', 'OPE_TYPE_2');
INSERT INTO SYSDATA VALUES ('*', 'LABEL_PRINT_ID', 'OPE_TYPE_3', 'OPE_TYPE_3');
INSERT INTO SYSDATA VALUES ('*', 'LASRMARK_CAT', 'HLM', 'hard laser mark');
INSERT INTO SYSDATA VALUES ('*', 'LASRMARK_CAT', 'LM', 'Soft laser mark');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '', 'Not specified');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '1', 'Good');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '2', 'RW (Re-cleaning)');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '3', 'SWP+SWC (Front)');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '4', 'SWP+SWC (Back)');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '5', 'MEP');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '6', 'DSP');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '7', 'Reusable defect');
INSERT INTO SYSDATA VALUES ('*', 'LC_RST_CAT', '8', 'Completely scrap');
INSERT INTO SYSDATA VALUES ('*', 'LD_CHK_EQP', 'MC3013', 'MC3011');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_LOT_HIS_CAT', '0', 'Attach');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_LOT_HIS_CAT', '1', 'Detach');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_LOT_HIS_CAT', '2', 'Update value');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '0', 'Adding');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '1', 'Update');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '2', 'Delete');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '3', 'Attach');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '4', 'Detach');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '5', 'Adding/attaching');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '6', 'Scrap');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '7', 'Attach');
INSERT INTO SYSDATA VALUES ('*', 'LIFE_MNG_CAT', '8', 'Detach');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'A', 'A: Anneal monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'C', 'C: normal monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'E', 'E: EP monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'F', 'F: Anneal filler dummy lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'G', 'G: Anneal M2 Lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'M', 'M: Thermal process monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'N', 'N: Normal lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'O', 'O: Inline inspection lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'S', 'S: Sample inspection lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'T', 'T: Process monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'W', 'W: WSA cleaning monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'X', 'X: downgrade lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_CAT', 'Y', 'Y: Re-process lot');
INSERT INTO SYSDATA VALUES ('*', 'LOT_DIV_CAT', '0', 'Normal');
INSERT INTO SYSDATA VALUES ('*', 'LOT_DIV_CAT', '1', 'in process inspection');
INSERT INTO SYSDATA VALUES ('*', 'LOT_LIST_VIEW', 'SORT_RULE', 'FIFO');
INSERT INTO SYSDATA VALUES ('*', 'LOT_MIX_CAT', '0', 'Possible');
INSERT INTO SYSDATA VALUES ('*', 'LOT_MIX_CAT', '1', 'Impossible to set report unit');
INSERT INTO SYSDATA VALUES ('*', 'LOT_MIX_CAT', '2', 'Impossible to set In process unit');
INSERT INTO SYSDATA VALUES ('*', 'LOT_MIX_CAT', '3', 'Possible if product id is same');
INSERT INTO SYSDATA VALUES ('*', 'LOT_MIX_CAT', '4', 'Possible if recipe is same');
INSERT INTO SYSDATA VALUES ('*', 'LOT_SEL_RULE', 'D', 'Sorting by due date');
INSERT INTO SYSDATA VALUES ('*', 'LOT_SEL_RULE', 'F', 'FIFO');
INSERT INTO SYSDATA VALUES ('*', 'LOT_SEL_RULE', 'P', 'Priority');
INSERT INTO SYSDATA VALUES ('*', 'LOT_SEL_RULE', 'Q', 'Q time setting order');
INSERT INTO SYSDATA VALUES ('*', 'LOT_SEL_RULE', 'R', 'Priority of same recipe');
INSERT INTO SYSDATA VALUES ('*', 'LOT_SEL_RULE', 'S', 'delay');
INSERT INTO SYSDATA VALUES ('*', 'LOT_STAT', 'A', 'A Just completed  at QA_Approval process');
INSERT INTO SYSDATA VALUES ('*', 'LOT_STAT', 'E', 'E final process was finished without QA_approval.');
INSERT INTO SYSDATA VALUES ('*', 'LOT_STAT', 'N', 'N Just completed  at QA_Approval process');
INSERT INTO SYSDATA VALUES ('*', 'LOT_STAT', 'O', 'O Lot out');
INSERT INTO SYSDATA VALUES ('*', 'LOT_STAT', 'R', 'R processing');
INSERT INTO SYSDATA VALUES ('*', 'LOT_STAT', 'S', 'S completed with special approval at QA_Approval process');
INSERT INTO SYSDATA VALUES ('*', 'LOT_TYPE', 'B', 'Block');
INSERT INTO SYSDATA VALUES ('*', 'LOT_TYPE', 'W', 'Wafer');
INSERT INTO SYSDATA VALUES ('*', 'MEAS_STAT', '0', 'Unmeasuremented');
INSERT INTO SYSDATA VALUES ('*', 'MEAS_STAT', '1', 'Measured');
INSERT INTO SYSDATA VALUES ('*', 'MENU_FLG', '0', 'No Read/Write');
INSERT INTO SYSDATA VALUES ('*', 'MENU_FLG', '1', 'Read only');
INSERT INTO SYSDATA VALUES ('*', 'MENU_FLG', '2', 'Read Write');
INSERT INTO SYSDATA VALUES ('*', 'MENU_FLG', '3', 'Able to release');
INSERT INTO SYSDATA VALUES ('*', 'MIMI_LOSS', '4', '-');
INSERT INTO SYSDATA VALUES ('*', 'MIX_CAT', '2', 'Mixing from same product code');
INSERT INTO SYSDATA VALUES ('*', 'MNG_CAT', '0', 'Adding');
INSERT INTO SYSDATA VALUES ('*', 'MNG_CAT', '1', 'Update');
INSERT INTO SYSDATA VALUES ('*', 'MNG_CAT', '2', 'Delete');
INSERT INTO SYSDATA VALUES ('*', 'MODULE_CAT', 'MODULE1', 'MODULE1');
INSERT INTO SYSDATA VALUES ('*', 'MODULE_CAT', 'MODULE2', 'MODULE2');
INSERT INTO SYSDATA VALUES ('*', 'MON_CAT', 'E', 'EP');
INSERT INTO SYSDATA VALUES ('*', 'MON_CAT', 'T', 'Thermal process');
INSERT INTO SYSDATA VALUES ('*', 'NOTEKIND', 'E', 'Bulliten board');
INSERT INTO SYSDATA VALUES ('*', 'NOTEKIND', 'L', 'Lot notes');
INSERT INTO SYSDATA VALUES ('*', 'NOTEKIND', 'P', 'Process notes');
INSERT INTO SYSDATA VALUES ('*', 'NOTEKIND', 'U', 'Equipment notes');
INSERT INTO SYSDATA VALUES ('*', 'OPE_INSP_STAT', '', 'Except in process inspection');
INSERT INTO SYSDATA VALUES ('*', 'OPE_INSP_STAT', '0', 'Processing in line inspection ( Need next lot)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_INSP_STAT', '1', 'Processing in line inspection ( No need next lot)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_INSP_STAT', 'Y', 'Not processing in line inspection');
INSERT INTO SYSDATA VALUES ('*', 'OPE_LABEL', 'OPE', 'casseette in process');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PRO_CAT', '0', 'Normal');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PRO_CAT', '1', 'Thermal process');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PRO_CAT', '2', 'Input order');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROC_UNIT', 'B', 'Batch');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROC_UNIT', 'L', 'Lot');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROC_UNIT', 'S', 'Sublot');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROC_UNIT', 'W', 'Wafer');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROG_STAT', '0', 'Before input');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROG_STAT', '1', 'Before ship compiling');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROG_STAT', '2', 'Waiting for ship compiler');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROG_STAT', '3', 'After PW compiling');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', '', 'Normal process');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'ALL_CA_GET', 'Process to get all cassettes info');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'BL_XRAY_RE', 'Block X-ray re-measurement');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'CMP_LMREAD', 'Manual compiler (LM reading)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'DSP_DSP', 'Normal product DSP');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'EG', 'EG input order');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'EP_OPE', 'EP reaction');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'F_CLEAN', 'final cleaning');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'INSP_FRE', 'Able to process in line inspection');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'PW_100MODE', 'Route of all lots inspection');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'SHIP_CMP_1', 'Ship compiler (PW ship compile)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'SHIP_CMP_3', 'Ship compiler (EP sub / Anneal compile)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'SHIP_CMP_4', 'Ship compiler (EP ship compile)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'SHIP_CMP_5', 'Ship compiler (AN Ship compile)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'WAF_GRND_F', 'Wafer polishing and cleaning (Front)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'WAF_GRND_R', 'Wafer polishing and cleaning (Back)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'WAF_GRND6F', 'Wafer polishing and cleaning (front 170kp)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'WAF_GRND6R', 'Wafer polishing and cleaning (Back 170kp)');
INSERT INTO SYSDATA VALUES ('*', 'OPE_PROPERTY', 'WHT', 'WHT');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_BLK', 'F6S102', 'Block stocker out port');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_BLK', 'F6S103', 'Block stocker out port (inventory)');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_BLK_N5', 'F0S202', '-');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_BLK_N6', 'F6S102', '-');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_BLK_N6', 'F6S103', '-');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_SHIP', 'F6S902', 'Stock out port for shipping ( Stock out/inventory)');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_SHIP', 'F6S903', 'Stock out port for shipping ( Stock out)');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_SHIP', 'F6S904', 'Stock out port for shipping ( Stock out/inventory)');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_SHIP', 'F6S905', 'Stock out port for shipping ( Inventory)');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_SHIP', 'F6S906', 'Stock out port for shipping ( Stock out/inventory)');
INSERT INTO SYSDATA VALUES ('*', 'OUT_PORT_SHIP', 'F6S908', 'Stock out port for shipping ( Stock out/inventory)');
INSERT INTO SYSDATA VALUES ('*', 'PDC_PORT', 'S4M201', 'S4P100');
INSERT INTO SYSDATA VALUES ('*', 'PERMISSION', 'PRIVATE', 'Private');
INSERT INTO SYSDATA VALUES ('*', 'PERMISSION', 'PUBLIC', 'Full access');
INSERT INTO SYSDATA VALUES ('*', 'PERMISSION', 'USERGROUP', 'Specified user group');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '0', '5/4/3/2/1');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '1', '1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20/21/22/23/24/25');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '2', '-1/0/30/99/125/-10/10////');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '3', '@//#//Q//@///P');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '4', '3/5/7/9/13');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '5', '25/24/23/21/22');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '6', '21/#/23/@/25');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '7', '////////////////////');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', '9', '1/4/8/10/12');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', 'A', '1/12/25');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', 'B', 'End position');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', 'C', '1/12');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', 'S', 'Both of edges(Top->End->Top->..)');
INSERT INTO SYSDATA VALUES ('*', 'PICK_POS', 'T', 'top edge');
INSERT INTO SYSDATA VALUES ('*', 'PICK_STAT', '1', 'Pick up status (Done)');
INSERT INTO SYSDATA VALUES ('*', 'PICK_STAT', '2', 'Pick up status (Not Applicable)');
INSERT INTO SYSDATA VALUES ('*', 'PICK_WAF_UNIT', 'A', 'All');
INSERT INTO SYSDATA VALUES ('*', 'PICK_WAF_UNIT', 'L', 'Lot');
INSERT INTO SYSDATA VALUES ('*', 'PICK_WAF_UNIT', 'S', 'Sublot');
INSERT INTO SYSDATA VALUES ('*', 'PICK_WAF_UNIT', 'W', 'Slot definition');
INSERT INTO SYSDATA VALUES ('*', 'PLANT_CAT', 'K', '-');
INSERT INTO SYSDATA VALUES ('*', 'PLANT_CAT', 'N', '-');
INSERT INTO SYSDATA VALUES ('*', 'PN_CAT', 'N', 'N type');
INSERT INTO SYSDATA VALUES ('*', 'PN_CAT', 'P', 'P type');
INSERT INTO SYSDATA VALUES ('*', 'PORT_TYPE', 'B', 'purpose for both of loading and unloading');
INSERT INTO SYSDATA VALUES ('*', 'PORT_TYPE', 'E', 'Port for empty cassette');
INSERT INTO SYSDATA VALUES ('*', 'PORT_TYPE', 'I', 'exclusive use for Loader');
INSERT INTO SYSDATA VALUES ('*', 'PORT_TYPE', 'L', 'Loader');
INSERT INTO SYSDATA VALUES ('*', 'PORT_TYPE', 'O', 'exclusive use for Unloader');
INSERT INTO SYSDATA VALUES ('*', 'PORT_TYPE', 'U', 'Unloader');
INSERT INTO SYSDATA VALUES ('*', 'PRE_WHT_PLANT_TIME', '1', 'WHT time');
INSERT INTO SYSDATA VALUES ('*', 'PRE_WHT_PLANT_TIME', '24', 'WHT time');
INSERT INTO SYSDATA VALUES ('*', 'PRECMP_CNT', '999964', '3');
INSERT INTO SYSDATA VALUES ('*', 'PRECMP_CNT', '999997', '10');
INSERT INTO SYSDATA VALUES ('*', 'PRECMP_CNT', 'A99909', '1');
INSERT INTO SYSDATA VALUES ('*', 'PRIORITY', '0', 'Most priority');
INSERT INTO SYSDATA VALUES ('*', 'PRIORITY', '1', 'Super express');
INSERT INTO SYSDATA VALUES ('*', 'PRIORITY', '2', 'Express');
INSERT INTO SYSDATA VALUES ('*', 'PRIORITY', '3', 'Semi-express');
INSERT INTO SYSDATA VALUES ('*', 'PRIORITY', '4', 'Normal');
INSERT INTO SYSDATA VALUES ('*', 'PROC_MEAS_CAT', 'MES', 'MES measurement data');
INSERT INTO SYSDATA VALUES ('*', 'PROC_MEAS_CAT', 'PRO', 'Process data');
INSERT INTO SYSDATA VALUES ('*', 'PROC_UNIT', 'B', 'Batch');
INSERT INTO SYSDATA VALUES ('*', 'PROC_UNIT', 'L', 'Lot');
INSERT INTO SYSDATA VALUES ('*', 'PROC_UNIT', 'S', 'Sublot');
INSERT INTO SYSDATA VALUES ('*', 'PROC_UNIT', 'W', 'Wafer');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CAT', 'D', 'Dummy product code');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CAT', 'F', 'Filler dummy product code');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CAT', 'I', 'Inline product code');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CAT', 'M', 'Monitor product code');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CAT', 'N', 'Normal product code');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CAT', 'S', 'send ahead product code');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'AXIS_CAT', 'AXIS category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'CUSTOMER_ID', 'Customer ID');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'DOPE_CAT_CZ', '-');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'DOPE_CAT_EP', '-');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'LASRMARK_CAT', 'Laser mark category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'MIX_CAT', 'Mix category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'PLANT_CAT', 'Process plant category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'PN_CAT', 'PN category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'PROD_CAT', 'product code category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'PRODUCT_KIND', 'product kind');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'RESIST_PER_CAT', 'Resistivity category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'SHIP_BOX_PTN', 'Shipping pack pattern');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'SHIP_LOT_ID_NUM_CAT', 'Ship lot ID number category');
INSERT INTO SYSDATA VALUES ('*', 'PROD_CODE_CAT', 'WRK_PLATE_TYPE', 'Work plate type');
INSERT INTO SYSDATA VALUES ('*', 'PROD_KIND', '1', 'Normal product');
INSERT INTO SYSDATA VALUES ('*', 'PROD_KIND', '2', 'Specific product');
INSERT INTO SYSDATA VALUES ('*', 'PROD_KIND', '3', 'Specific product 2');
INSERT INTO SYSDATA VALUES ('*', 'PRODUCT_CAT', '1', 'PW(SUB)');
INSERT INTO SYSDATA VALUES ('*', 'PRODUCT_CAT', '2', 'Ep/ANL');
INSERT INTO SYSDATA VALUES ('*', 'PRODUCT_KIND', 'AN', 'AN');
INSERT INTO SYSDATA VALUES ('*', 'PRODUCT_KIND', 'EP', 'EP');
INSERT INTO SYSDATA VALUES ('*', 'PRODUCT_KIND', 'PW', 'PW');
INSERT INTO SYSDATA VALUES ('*', 'QA_CAT', '', '-');
INSERT INTO SYSDATA VALUES ('*', 'QA_CAT', 'N', 'N Just completed  at QA_Approval process');
INSERT INTO SYSDATA VALUES ('*', 'QA_CAT', 'S', 'S: Executing special approval');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_CAT', 'D', 'D Q-time value');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_CAT', 'Q', 'Qtime value');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_CONT_STAT', 'B', 'B Q time defect');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_CONT_STAT', 'F', 'F waiting for Q-time judgment');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_CONT_STAT', 'G', 'G Passing Q-time restriction');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_TYPE', 'D', 'Starting operation should be later');
INSERT INTO SYSDATA VALUES ('*', 'QTIME_TYPE', 'Q', 'Starting operation should be within');
INSERT INTO SYSDATA VALUES ('*', 'RC_STAT', 'B', 'B HOLD mail');
INSERT INTO SYSDATA VALUES ('*', 'RC_STAT', 'H', 'H HOLD');
INSERT INTO SYSDATA VALUES ('*', 'RC_STAT', 'M', 'M meter');
INSERT INTO SYSDATA VALUES ('*', 'RC_STAT', 'O', 'O OK');
INSERT INTO SYSDATA VALUES ('*', 'RC_STAT', 'W', 'W Warning');
INSERT INTO SYSDATA VALUES ('*', 'REGST_CAT', '0', 'Normal');
INSERT INTO SYSDATA VALUES ('*', 'REGST_CAT', '1', 'FOSB cleaning');
INSERT INTO SYSDATA VALUES ('*', 'REJECT_HIS_CAT', 'C', 'C cancel of defect');
INSERT INTO SYSDATA VALUES ('*', 'REJECT_HIS_CAT', 'D', 'D Scrap registration');
INSERT INTO SYSDATA VALUES ('*', 'SEARCH_CAT', 'E', 'Equipment');
INSERT INTO SYSDATA VALUES ('*', 'SEARCH_CAT', 'M', 'Material');
INSERT INTO SYSDATA VALUES ('*', 'SELECT_CAT', 'N', 'Unselected');
INSERT INTO SYSDATA VALUES ('*', 'SELECT_CAT', 'Y', 'Selection');
INSERT INTO SYSDATA VALUES ('*', 'SELF_DIV_STAT', '0', 'Not auto reuse');
INSERT INTO SYSDATA VALUES ('*', 'SELF_DIV_STAT', '1', 'Auto reuse');
INSERT INTO SYSDATA VALUES ('*', 'SELF_DIV_STAT', '2', 'Not auto reuse with warning');
INSERT INTO SYSDATA VALUES ('*', 'SELF_DIV_STAT', '3', 'Compiler processing');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '0', 'Assurance lot');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '1', 'Cassette lot');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '2', 'Thermal process batch No');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '3', 'Assurance block');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '4', 'FOSB');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '5', 'Ingot lot');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '6', 'Thermal process monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'SEQ_CAT', '7', 'Monitor single No');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_BOX_PTN', 'BOTH', 'Both of edges are empty.');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_BOX_PTN', 'LOWER', 'Lower side is empty.');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_BOX_PTN', 'UPPER', 'Upper side is empty');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_CAR_TYPE', 'C1', 'Cassette');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_CAR_TYPE', 'F1', 'FOSB');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_CAR_TYPE', 'U1', 'FOUP');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_GEN1', 'general product 1');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_GEN2', 'general product 2');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_QADB1', 'QADB1');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_QADB2', 'QADB2');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_QADB3', 'QADB3');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_SYSTEM1', 'Ship system 1');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_SYSTEM2', 'Ship system 2');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LABEL', 'SHIP_SYSTEM3', 'Ship system 3');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '0', 'Normal');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '1', '8 characters');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '2', '5 characters');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '3', '7 characters');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '4', '9 characters');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '5', '10 characters');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_LOT_ID_NUM_CAT', '6', 'No assgined number');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_MON_CAT', '0', 'Ship inspection');
INSERT INTO SYSDATA VALUES ('*', 'SHIP_MON_CAT', '1', 'Monitor');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '0', 'Sample from same CZ assurance block');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '1', 'Sample from same PW assurance lots');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '2', 'Anneal batch (Not specified position)');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '3', 'Anneal batch (Bottom)');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '4', 'Anneal batch (Top)');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '5', 'Anneal batch (specified position)');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '6', 'Small lot');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '7', 'Epn batch');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '8', 'EP small lot');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', '9', 'taking more sample');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', 'A', 'DSP assurance');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_CAT', 'B', 'A-DSP bulk assurance');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '**', 'Error');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '1', 'Confirmed pass');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '2', 'Confirmed reject');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '3', 'Unconfirmed pass');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '4', 'Not confirmed reject');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '5', 'Unjudged');
INSERT INTO SYSDATA VALUES ('*', 'SMPL_JDG_STATUS', '9', 'Other');
INSERT INTO SYSDATA VALUES ('*', 'SORT_SEP_CAT', 'A', 'Category A');
INSERT INTO SYSDATA VALUES ('*', 'SORT_SEP_CAT', 'B', 'Category B');
INSERT INTO SYSDATA VALUES ('*', 'SORT_SEP_CAT', 'C', 'Category C');
INSERT INTO SYSDATA VALUES ('*', 'SORT_SEP_CAT', 'D', 'Category D');
INSERT INTO SYSDATA VALUES ('*', 'SPEC_CHK_RST', '0', '0: OK');
INSERT INTO SYSDATA VALUES ('*', 'SPEC_CHK_RST', '1', '1 Out of Upper Limit');
INSERT INTO SYSDATA VALUES ('*', 'SPEC_CHK_RST', '2', '2 Out of Lower Limit');
INSERT INTO SYSDATA VALUES ('*', 'SPEC_CHK_RST', '3', '3 Inspection NG');
INSERT INTO SYSDATA VALUES ('*', 'SPEC_CHK_RST', '4', '4 Unmatched Character');
INSERT INTO SYSDATA VALUES ('*', 'STD_ERR_CAT', '0', '0: No data');
INSERT INTO SYSDATA VALUES ('*', 'STD_ERR_CAT', '1', '1 Out of Upper Limit');
INSERT INTO SYSDATA VALUES ('*', 'STD_ERR_CAT', '2', '2 Out of Lower Limit');
INSERT INTO SYSDATA VALUES ('*', 'STG_PROPERTY', 'CW_CMP', 'CW stage');
INSERT INTO SYSDATA VALUES ('*', 'STG_PROPERTY', 'EP_CMP', 'EP stage');
INSERT INTO SYSDATA VALUES ('*', 'STG_PROPERTY', 'PW_CMP', 'PW stage');
INSERT INTO SYSDATA VALUES ('*', 'STK_ID', 'F0S1', '*');
INSERT INTO SYSDATA VALUES ('*', 'STK_PROPERTY', 'ACT_CONVEY', 'Actual buffer conveyer');
INSERT INTO SYSDATA VALUES ('*', 'STK_PROPERTY', 'EMP_CONVEY', 'Empty buffer conveyer');
INSERT INTO SYSDATA VALUES ('*', 'STK_PROPERTY', 'STK_OC25', 'Stocker for cassettes (OC25)');
INSERT INTO SYSDATA VALUES ('*', 'STOCK_ACT', '', '-');
INSERT INTO SYSDATA VALUES ('*', 'STOCK_ACT', '0', 'Stock out');
INSERT INTO SYSDATA VALUES ('*', 'STOCK_ACT', '1', 'Moving to next stocker');
INSERT INTO SYSDATA VALUES ('*', 'STOT_UNIT', '', 'Not specified');
INSERT INTO SYSDATA VALUES ('*', 'STOT_UNIT', 'L', 'Lot unit (bunch of family lot)');
INSERT INTO SYSDATA VALUES ('*', 'STOT_UNIT', 'S', 'Sublot unit');
INSERT INTO SYSDATA VALUES ('*', 'SUB_RP_ROUTE_CAT', 'I', 'Ingot route');
INSERT INTO SYSDATA VALUES ('*', 'SUB_RWK_CAT', 'I', 'Ingot route');
INSERT INTO SYSDATA VALUES ('*', 'SUB_RWK_CAT', 'M', 'Main route');
INSERT INTO SYSDATA VALUES ('*', 'SUB_RWK_CAT', 'R', 'Rework route');
INSERT INTO SYSDATA VALUES ('*', 'SUB_RWK_CAT', 'S', 'Sub route');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CAT', 'M', 'M Mixed lot');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CAT', 'N', 'N Normal sublot');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '1', '1 : Good');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '2', '2 :  Re-cleaning');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '3', '3: Re-grind');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '4', '4: NG');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '5', '5 : Sample');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '6', '6 : Good (FOSB)');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '7', '7: Good (package)');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_CATEGORI', '8', '8: Good (fraction product)');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_STAT', 'H', 'H HOLD');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_STAT', 'O', 'O Sublot out');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_STAT', 'R', 'Processing');
INSERT INTO SYSDATA VALUES ('*', 'SUBLOT_STAT', 'W', 'W Waiting');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'ALL_TEST', 'Inspection for all lots (Rework route)');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'MAIN', 'Normal route (main route)');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'NGS_BL', 'NGS_BL(ingot route)');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'OPE_INSP', 'in process inspection (sub route)');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'RJCT_ALL', 'Completely scrap');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'RP', 'RP (Re-polish route)');
INSERT INTO SYSDATA VALUES ('*', 'SYS_ROUTE_CAT', 'RW', 'RW (Re-clean route)');
INSERT INTO SYSDATA VALUES ('*', 'SYSTEM_CODE_CAT', 'A_LOT_ID', 'A_LOT_ID the latest normal lot ID');
INSERT INTO SYSDATA VALUES ('*', 'SYSTEM_CODE_CAT', 'X_LOT_ID', 'X_LOT_ID');
INSERT INTO SYSDATA VALUES ('*', 'SYSTEM_CODE_CAT', 'Y_LOT_ID', 'Y_LOT_ID');
INSERT INTO SYSDATA VALUES ('*', 'SYSTEM_CODE_CAT', 'Z_LOT_ID', 'Z_LOT_ID');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BAREA', 'Area table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BCALND', 'Calendar table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BCARG', 'Carrier group table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BCARRY_PORT_DSP_AREA', 'Destination by DSP area');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BCODE', 'Code table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BCZ_ITEMIZED_DEF', '-');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BDUMMY_WAF_SET', 'Dummy Wafer number definition table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEMP_CARRY_PORT', 'destination for empty cassette table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEMPCAR_SC', 'Empty cassette transfer schedule table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEP_MEAS_NUM', 'EP inspection Frequency setting table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEPMONI', 'EP monitor compile master');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQP', 'Equipment table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQP_AREA', 'Equipment area relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQP_MAILADRESS', 'Mailing address table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQP_RECIP', 'Equipment registered recipe table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQP_USER', 'Equipment operator management table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQPG', 'Equipment group table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQPG_EQP', 'Equipment group relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BEQPRT', 'Equipment port table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BHOLDCODE', 'Hold reason code table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BINSPJDG', 'Inspection judgment table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BINSPUSED', 'Inspection item table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BLABEL_PRINTER', 'Label printer table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMEAS_ID', 'Measurement ID table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMEAS_ID_ITEM', 'Measurement ID/measurement item relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMEAS_ITEM', 'Measurement item table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMEAS_LOOKUP', 'Measurement lookup table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMEAS_PROD', 'Measurement item product table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMROUTE', 'Module route table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMROUTE_OPE', 'Module route relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMTL_ID', 'Material table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMTL_ID_ITEM', 'Material item relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMTL_ITEM', 'Material item table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BMTL_PROD_FIT', 'Material using management by product code table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BOPE', 'Process table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BOPEMONI_INPUT_ADMIN', 'Auto input management table for Process monitor lot');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPRINT_TYPE', 'Label printer contents table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPROCDATA_ID', 'Process data ID table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPROCDATA_ID_ITEM', 'Process data ID relation item table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPROCDATA_ITEM', 'Process data item table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPROCDATA_LOOKUP', 'Process lookup table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPROD', 'Product table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPROD_02', 'Product code table2');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPRODCODE', 'Product code table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BPWSMPLCASETCON', 'PW sample cassette config table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BQTIME', 'Q time table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BRECIP_LOOKUP', 'Recipe lookup table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BRECIP_PRAM', 'Recipe parameter table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BREJECTCODE', 'Reject reason code table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BREJECTCODE_STG', 'Reject reason code table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BREJECTCODE_STGG', 'Reject reason code Stage Group table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BREJECTCODE_STGG_STG', 'Reject reason code Stage table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BRL_ROUTE', 'Release route view');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BROUTE', 'Route table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BROUTE_MROUTE', 'Route module route relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BROUTECNCT', 'Route connection table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSLICE_ITEMIZED_DEF', 'SLICE_ITEMIZED_LIST definition table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTG', 'Stage table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTGG', 'Stage group table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTGG_STG', 'Stage group relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTK', 'Stocker table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTK_AREA', 'Stocker Area relation table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTK_CARG', 'Stocker cassette group table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSTKOUTLET', 'Stocker port table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSYSTEM_DEF', 'System definition table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BSYSTEM_INI_TBL', 'System ini table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BUSER', 'User table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'BUSERG', 'User group table');
INSERT INTO SYSDATA VALUES ('*', 'TBL_NAME', 'SYSDATA', 'System data table');
INSERT INTO SYSDATA VALUES ('*', 'TGT_PROD_CAT', 'A', 'Anneal');
INSERT INTO SYSDATA VALUES ('*', 'TGT_PROD_CAT', 'E', 'EPI');
INSERT INTO SYSDATA VALUES ('*', 'TGT_PROD_CAT', 'P', 'PW');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'AI', 'AI AUTO IN');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'AO', 'AO AUTO OUT');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'MI', 'MI Manual IN');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'MO', 'MO Manual Out');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'XC', 'XC transfer comp');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'XS', 'XS transfer start');
INSERT INTO SYSDATA VALUES ('*', 'TRAN_STAT', 'XX', 'XX Forcibly complete');
INSERT INTO SYSDATA VALUES ('*', 'TRANS_RETRY', 'RETRY_LIMITCNT', '144');
INSERT INTO SYSDATA VALUES ('*', 'TX04A_IN_PORT', 'S4E201', 'S4M201');
INSERT INTO SYSDATA VALUES ('*', 'TX04F_TX_MODE', '1', 'Waiting for primary inspection');
INSERT INTO SYSDATA VALUES ('*', 'TX04G_TX_MODE', '1', 'Waiting for primary inspection');
INSERT INTO SYSDATA VALUES ('*', 'TX05F_TX_MODE', '2', 'Waiting for ingot');
INSERT INTO SYSDATA VALUES ('*', 'TX05G_TX_MODE', '2', 'Waiting for ingot');
INSERT INTO SYSDATA VALUES ('*', 'TX06F_TX_MODE', '3', 'Ingot info.');
INSERT INTO SYSDATA VALUES ('*', 'USERG_ID', 'ADMIN', 'Administrator');
INSERT INTO SYSDATA VALUES ('*', 'USERG_ID', 'SE_STAFF', 'SE staff');
INSERT INTO SYSDATA VALUES ('*', 'USERG_ID', 'SPCUIADMN', 'SPC UI administrator');
INSERT INTO SYSDATA VALUES ('*', 'USERG_ID', 'SPCUIUSER', 'SPC UI user');
INSERT INTO SYSDATA VALUES ('*', 'USERG_ID', 'SYS', 'SYSTEM');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '', 'Good');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '0', '(not use)');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '1', '(not use)');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '2', 'Re-Polish');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '3', '(not use)');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '4', 'Re-cleaning');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '5', '(not use)');
INSERT INTO SYSDATA VALUES ('*', 'WAF_ACTION_CAT', '6', 'Completely scrap');
INSERT INTO SYSDATA VALUES ('*', 'WAF_GRND_LIFECNT', '1', '60');
INSERT INTO SYSDATA VALUES ('*', 'WAF_GRND_LIFECNT', '2', '70');
INSERT INTO SYSDATA VALUES ('*', 'WAF_GRND_LIFECNT', '3', '80');
INSERT INTO SYSDATA VALUES ('*', 'WAF_OPE_SUB_HIS_EQP', '1', 'WAF_GRND');
INSERT INTO SYSDATA VALUES ('*', 'WAF_OPE_SUB_HIS_EQP', '2', 'WAF_GRND6');
INSERT INTO SYSDATA VALUES ('*', 'WAF_OPE_SUB_HIS_EQP', '3', 'VS_INSP');
INSERT INTO SYSDATA VALUES ('*', 'WAF_QUO_PTN', '', 'Good');
INSERT INTO SYSDATA VALUES ('*', 'WAF_QUO_PTN', 'A', 'A defect');
INSERT INTO SYSDATA VALUES ('*', 'WAF_QUO_PTN', 'B', 'B defect');
INSERT INTO SYSDATA VALUES ('*', 'WAF_QUO_PTN', 'C', 'C defect');
INSERT INTO SYSDATA VALUES ('*', 'WAF_QUO_PTN', 'D', 'D defect');
INSERT INTO SYSDATA VALUES ('*', 'WHAT_NEXT_MODE', '0', 'User can select next lot and start operation.');
INSERT INTO SYSDATA VALUES ('*', 'WHAT_NEXT_MODE', '1', 'System decides next lot. User can not select it.');
INSERT INTO SYSDATA VALUES ('*', 'WORKPLATE_LABEL', 'WP', 'Work plate');
INSERT INTO SYSDATA VALUES ('*', 'WRK_GRP', 'ADMA', 'Administrator A');
INSERT INTO SYSDATA VALUES ('*', 'WRK_GRP', 'ADMB', 'Administrator B');
INSERT INTO SYSDATA VALUES ('*', 'WRK_GRP', 'OPE', 'General manufacturing');
INSERT INTO SYSDATA VALUES ('*', 'WRK_GRP', 'QAS', 'QA staff');
INSERT INTO SYSDATA VALUES ('*', 'WRK_GRP', 'SES', 'SE staff');
INSERT INTO SYSDATA VALUES ('*', 'WRK_GRP', 'TEC', 'Technical staff');
INSERT INTO SYSDATA VALUES ('*', 'YESNO', 'N', 'No');
INSERT INTO SYSDATA VALUES ('*', 'YESNO', 'Y', 'Yes');
INSERT INTO SYSDATA VALUES ('EMP_CAR_GP', 'CW_EMP_CLN', 'CARG01', 'TEST_CWE');
INSERT INTO SYSDATA VALUES ('EMP_CAR_GP', 'CW_EMP_CLN', 'FOUP_25_AA', '01');
INSERT INTO SYSDATA VALUES ('EMP_CAR_GP', 'CW_EMP_CLN', 'OPC_25_DEM', '1');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_AN_MONITOR_RETURN', 'AN Monitor Return');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_AUTO_CONTROL', 'Auto Control');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_BBS_UPDATE', 'BBS Update');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_BLOCK_RECEIV', 'Block Receiving');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_BLOCK_RECEIV_CANCEL', 'Block Receiving Cancel');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_BLOCK_USER_LOT_LIST', 'User Lots List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CHANGE_PASSWORD', 'Password Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CHECK_OPERATION_START', 'Check For Operation Start(Mount)');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CHK_OPE_COMP_MOUNT', 'Check for Ope Comp Mount');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CHK_OPE_COMP_SEP_CLN', 'Check Ope Comp Sep Cln');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CHK_OPE_COMP_SLICE', 'Check for Ope Comp Slice');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_COMPILE_AN_MONITOER', 'Anneal Monitor Box Kitting');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_COMPILE_EP_MONITOER', 'Compile EP Monitor Box');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_COMPILE_PRE-MONITOR_KITTING', 'Pre Monitor Kitting');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_COMPILE_PREPATION', 'Compile Prepation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CONTROL_OF_EP_LOT_PLANNING', 'Control Of EP Lot Input Planning');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CRR_EXG', 'Carrier Exchange');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CRR_FOSB_CLN', 'FSOB Cleaning');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CRR_GRP_CHG', 'Carrier Group Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CRR_INFO', 'Carrier Operation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CRR_LIST', 'Carrier List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CRR_RGST', 'Carrier Registration');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_OPER_DEL', 'Carrier Delete');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_OPER_FORCE_CHG', 'Carrier Force Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_OPER_FOSB_LABEL_REPRINT', 'FOSB Label Re-Print');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_OPER_PM_RST', 'PM Info Reset');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_OPER_STAT_CHG', 'Carrier Status Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_RSV_CNL', 'Carrier Reservation Cancel');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EML_ITEM_MAINTENANCE', 'EML Item Maintenance');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EP_MONITOR_RETURN', 'EP Monitor Return');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EQP_HIS_LIST', 'EQP Operation History List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EQP_INFO', 'EQP Operation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EQP_NOTE', 'EQP Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EQP_STAT_CHANGE', 'EQP Status Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_GENERATE_DUMMY_BOX', 'Anneal Side Dummy Kitting');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_INPROCESS_INSPECT', 'In-Process Inspect');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_INPUT_INSP_SMP_DATA', 'Input Inpsection Sampling Data');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_INSP_FAIL_LIST', 'Inspection Failure List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_INSP_ID_SAMPLE_LIST', 'Wafer List By Inspection ID');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_INSP_SMP_DATA_REPORT', 'Input Inspection Sample Data');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_INV_INQ', 'Inventory Inquiry');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LABEL_RE_PRINT', 'Label Re-Print');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LABEL_TEMPLETE_SETTING', 'Label Print Setting');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LASER_MARK_INFO', 'Laser Mark Information');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LIFE_ATTACH_DETACH', 'Life Attach Detach');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LIFT_LOT_HISTORY', 'Life Lot History');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOCAL_LOT_CREATE', 'Local Lot Create');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_ATTRIBUTE_CHG', 'Lot Attribute Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_CASSETTE_LOT_CONSOLIDATION', 'CST Lot ID Consolidation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_COMPILE_RECOVERY', 'Lot Compile Recovery');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_FUTURE_HOLD', 'Lot Future Hold');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_HOLD', 'Lot Hold');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_HOLD_LIST', 'Lot Hold List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_HOLD_RELEASE', 'Lot Hold Release');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_INFO', 'Lot Information');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_INPUT_PLAN', 'EP Lot Input Plan');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_LIST', 'Lot List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_MERGE', 'Lot Merge');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_NOTE_ADD', 'Add Lot Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_NOTE_DEL', 'Delete Lot Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_NOTE_UDP', 'Update Lot Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_PARTIAL_REWORK', 'Partial Rework');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_PTY_CHG', 'Priority Bulk Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_REWORK', 'Lot Rework');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_REWORK_CANCEL', 'Lot Rework Cancel');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_SPLIT', 'Lot Split');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_SUBROUTE', 'Lot SubRoute');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOTE_NOTE', 'Lote Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_MEAS_DATA_DISPLAY', 'Meas Data Display');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_MEAS_DATA_INPUT', 'Measurement Data Input');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_MEASUREMENT_DATA_RE_REPORT', 'Measurement Data Re-Report');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_MTRL_NG_LOT_LIST', 'Material NG Lot List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_NTC_TOYO_ROUTE_SWITCH', 'NTC TOYO Route Switch');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OBTAIN_ALL_CARRIER', 'Obtain All Carrier');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_ALL_INSP', 'Ope Comp All Inspection');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_BLOCK', 'Ope Comp Block');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CONFIRM', 'Operation Completion Confirmation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CONFIRM_BLOCK', 'Ope Comp Confirmation Block');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CONFIRM_CRR_CHG', 'Ope Comp Confirmation Carrier Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CONFIRM_CST_LOT_REGEN', 'Ope Comp Confirm Cst Lot Regen');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CONFIRM_SEP_CLN', 'Ope Comp Confirmation Sep Cln');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CRR_CHG', 'Ope Comp Carrier Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_CST_LOT_REGEN', 'Ope Comp Cst Lot Regen');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_INPUT_ACT_DATA_SEP_CLN', 'Input Act Data Sep Cln');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_INSP_SORTER', 'Ope Comp Inspection Sorter');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_POLISHING', 'Ope Comp Polishing');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_RE_MEAS_XRAY', 'Ope Comp Re-Measurement X-Ray');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_SLICE', 'Ope Comp Slice');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_COMP_THICK_SORT', 'Ope Comp Thickness Sort');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_END_MOUNT', 'Operation End Mount');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_START_CANCEL_INSP_SORTER', 'Ope Start Cancel Insp Sorter');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPERATION_COMPLETE', 'Operation  Complete');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPERATION_START', 'Operation Start');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPERATION_START_ALL_INSP', 'Ope Start All Inspection');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPERATION_START_CONFIRM', 'Operation Start Confirmation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPERATION_START_INSP_SORTER', 'Ope Start Insp Sorter');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PAUSE', 'EQP Pause');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROC_HOLD_REGISTRATION', 'Process Hold');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROC_HOLD_RELEASE', 'Process Hold Release');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROC_INPUT_PREP', 'Process Input Preparation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROC_NOTE_ADD', 'Add Process Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROC_NOTE_DEL', 'Delete Process Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROC_NOTE_UDP', 'Update Process Note');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PROCESS_DATA_LIST', 'Process Data List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_PRODUCT_ID_INFO', 'Product ID Information');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_RECIPE_CONFIRMATION', 'Recipe Confirmation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_RESERVED_EMPTY_CARRIER', 'Reserved Empty Carrier');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_RETRIEVE_DATA', 'Retrieve Data');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_ROUTE_ID_CHG', 'Route ID Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_ROUTE_INFO', 'Route Info Display');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_SCRAP_BLOCK_LOT', 'Scrap Block Lot');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_SEARCH_HIS', 'Warning History List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_SET_AS_NEXT', 'Set As Next List');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_SHIPPING_JUDGE', 'PW Shipping Judge');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_SPEC_OF_CHAMBER', 'Specification Of Chamber For Update');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_STOCKER_IN_HISTORY', 'Stocker In History');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_WAFER_FAILURE_REPORT', 'Wafer Failure Report');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_WAFER_REJECT_CANCEL', 'Wafer Reject Cancel');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_WAFER_REJECT_INPUT', 'Wafer Reject Input');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', '*', 'All Fuction');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_E_WORKORDER', 'e-Workorder');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_MQ_ENVIRONMENT_SWITCH', 'MQ Environment Switch');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_LOT_SEL_RELEASE', 'Lot Select Release');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_EQP_MODE_CHG', 'Equipment Mode Change');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_OPE_START_CANCEL', 'Ope Start Cancel');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_SP1_PREPARATION', 'SP1 Preparation');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_TRANSFER', 'Transfer');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_STOCKER_OUT', 'Stocker out');
INSERT INTO SYSDATA VALUES ('UAC', 'OPI', 'OPI_CST_LOC_CHG', 'Cassette Location Change');
